### ISSUE TITLE
[css-nesting] Problem with mixing properties and selectors

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1002]
A resolution was made for [csswg-drafts/#8249](https://github.com/w3c/csswg-drafts/issues/8249).

**\[css\-nesting\] Problem with mixing properties and selectors**

* RESOLVED: Adopt Option 3

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8249#issuecomment-1379326665)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
Covered under https://bugzilla.mozilla.org/show_bug.cgi?id=1648037
