### ISSUE TITLE
[css-text-4] hyphenate-character doesn't just put hyphen at end of line 

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1006]
A resolution was made for [csswg-drafts/#2975](https://github.com/w3c/csswg-drafts/issues/2975).

**\[css\-text\-4\] hyphenate\-character doesn't just put hyphen at end of line **

* RESOLVED: A single\-string value changes what is inserted, but not where

[Discussion.](https://github.com/w3c/csswg-drafts/issues/2975#issuecomment-1403956955)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by jfkthame** [comment]
No change needed here.
