### ISSUE TITLE
[css-text] Hyphenation styling should apply to the wbr element 

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1007]
A resolution was made for [csswg-drafts/#5972](https://github.com/w3c/csswg-drafts/issues/5972).

**\[css\-text\] Hyphenation styling should apply to the wbr element **

* RESOLVED: Close WONTFIX

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5972#issuecomment-1403959679)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by jfkthame** [comment]
No change here.
