### ISSUE TITLE
[css-text-3] Conformant use of text-transform

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1031]
A resolution was made for [csswg-drafts/#8279](https://github.com/w3c/csswg-drafts/issues/8279).

**\[css\-text\-3\] Conformant use of text\-transform**

* RESOLVED: Make the authoring advice for text\-transform normative

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8279#issuecomment-1426909860)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
This was just adding some authoring advice to the spec; nothing that we need to take action on.
