### ISSUE TITLE
[css-text-4] Renaming text-space-* to white-space-*

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1040]
A resolution was made for [csswg-drafts/#8273](https://github.com/w3c/csswg-drafts/issues/8273).

**\[css\-text\-4\] Renaming text\-space\-\* to white\-space\-\***

* RESOLVED: rename \`text\-space\-collapse\` back to \`white\-space\-collapse\` 

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8273#issuecomment-1440470681)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
Found a bug to implement this property https://bugzilla.mozilla.org/show_bug.cgi?id=1816899
