### ISSUE TITLE
[css-ui] Tweaking outline-style: auto colors.

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1041]
A resolution was made for [csswg-drafts/#7761](https://github.com/w3c/csswg-drafts/issues/7761).

**\[css\-ui\] Tweaking outline\-style: auto colors.**

* RESOLVED: outline\-style: auto outlines, if influenced by an author color, are influenced by outline\-color, which itself gets a new initial value keyword 'auto' which computes to 'currentColor' when outline\-style is not auto and otherwise represents the 'accent\-color'

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7761#issuecomment-1440512109)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
Tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1833431
