### ISSUE TITLE
[css-overflow] add method to prevent elements from contributing to scrollable overflow

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1047]
A resolution was made for [csswg-drafts/#8361](https://github.com/w3c/csswg-drafts/issues/8361).

**\[css\-overflow\] add method to prevent elements from contributing to scrollable overflow**

* RESOLVED: Adopt this feature as overflow\-bikeshed

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8361#issuecomment-1451097120)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
The name's not finalized yet, but I guess we might as well file a placeholder bug right now, pending spec updates with name/details.

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1819787
