### ISSUE TITLE
[css-inline-3] baseline-source:first and overflow:hidden inline-boxes.

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1048]
A resolution was made for [csswg-drafts/#8214](https://github.com/w3c/csswg-drafts/issues/8214).

**\[css\-inline\-3\] baseline\-source:first and overflow:hidden inline\-boxes.**

* RESOLVED: Accept this behavior for baseline\-source:first&124;last

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8214#issuecomment-1451099690)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't implement `baseline-source` yet; that's https://bugzilla.mozilla.org/show_bug.cgi?id=1809568.
