### ISSUE TITLE
[css-position-3] Containing block formed by fragmented inlines

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1051]
Resolutions were made for [csswg-drafts/#8284](https://github.com/w3c/csswg-drafts/issues/8284).

**\[css\-position\-3\] Containing block formed by fragmented inlines**

* RESOLVED: Try out the proposal above, spec the fragmentation behavior
* RESOLVED: in LTR\-tb the top\-left corner is the top\-left corner of the top\-left\-most fragment of the first line, and the bottom and right edges are bottommost and rightmost edges of all the fragments. Directionality comes from the inline

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8284#issuecomment-1460601033)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
no bug, I think we can co-opt https://bugzilla.mozilla.org/show_bug.cgi?id=489100 to cover this.
