### ISSUE TITLE
[css-om][css-backgrounds] Serialization of `background: none`

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1052]
A resolution was made for [csswg-drafts/#8496](https://github.com/w3c/csswg-drafts/issues/8496).

**\[css\-om\]\[css\-backgrounds\] Serialization of \`background: none\`**

* RESOLVED: Move color at the end of the final\-bg\-layer grammar, to make it serialize as \`none\` 

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8496#issuecomment-1460607422)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1821230
