### ISSUE TITLE
[scroll-animation-1] Define scroll linked animation behavior in printing documents

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1064]
A resolution was made for [csswg-drafts/#8226](https://github.com/w3c/csswg-drafts/issues/8226).

**\[scroll\-animation\-1\] Define scroll linked animation behavior in printing documents**

* RESOLVED: for printing/paged, root is considered fully in view \(scroll timelines on it are inactive\)

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8226#issuecomment-1476438765)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
There is [Bug 1805950](https://bugzilla.mozilla.org/show_bug.cgi?id=1805950) there already
