### ISSUE TITLE
[scroll-animations-1][css-animations-2] animation short-hand support for new properties

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1070]
A resolution was made for [csswg-drafts/#8054](https://github.com/w3c/csswg-drafts/issues/8054).

**\[scroll\-animations\-1\]\[css\-animations\-2\] animation short\-hand support for new properties**

* RESOLVED: New features are not added to the animation shorthand \(for now\), they're just reset

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8054#issuecomment-1476502277)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
No action needed
