### ISSUE TITLE
[css-counter-styles-3] Should "Ready-made Counter Styles" be supported by UA?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1082]
Resolutions were made for [csswg-drafts/#8636](https://github.com/w3c/csswg-drafts/issues/8636).

**\[css\-counter\-styles\-3\] Should "Ready\-made Counter Styles" be supported by UA?**

* RESOLVED: split predefined counter styles into a separate spec
* RESOLVED: Move @counter\-style rule and symbols\(\) function to the counter styles spec. Retain in that spec the 2.0, 2.1 and the six way cjk ideographic split \(which is marked at\-risk\). Move rest of counter styles to registry on W3C wiki.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8636#issuecomment-1481401118)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by tabatkins** [comment]
This was a misfire by the bot; some resolutions from previous meetings were quoted in a comment. Feel free to close.

**Comment by dholbert** [comment]
Thanks!
