### ISSUE TITLE
[css-animations-2] Proposal: Time-based Keyframe Animations

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1102]
A resolution was made for [csswg-drafts/#4907](https://github.com/w3c/csswg-drafts/issues/4907).

**\[css\-animations\-2\] Proposal: Time\-based Keyframe Animations**

* RESOLVED: Draft up proposal for time\-based keyframe selectors in Anim 2

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4907#issuecomment-1505573230)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
I will check this again once this is ready in css-animations-2
