### ISSUE TITLE
[css-view-transitions-1] Enforce ::view-transition to be fixed position

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1103]
A resolution was made for [csswg-drafts/#8505](https://github.com/w3c/csswg-drafts/issues/8505).

**\[css\-view\-transitions\-1\] Enforce ::view\-transition to be fixed position**

* RESOLVED: Define "snapshot CB" as the current snapshot root rect, give it ICB behaviors so it captures all elements \(preventing them from going higher\)

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8505#issuecomment-1505587046)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't implement this feature (view transitions) yet; no bug needed.
