### ISSUE TITLE
[css-view-transitions-1] Should isolation and plus-lighter blending be applied conditionally

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1104]
A resolution was made for [csswg-drafts/#7814](https://github.com/w3c/csswg-drafts/issues/7814).

**\[css\-view\-transitions\-1\] Should isolation and plus\-lighter blending be applied conditionally**

* RESOLVED: isolation/blending\-mode properties are added conditionally, as stated in current spec

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7814#issuecomment-1505594450)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't implement this feature (view transitions) yet; no bug needed.
