### ISSUE TITLE
[selectors-4] Add pseudo-class to establish before-change style for css-transitions on new elements.

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1109]
Resolutions were made for [csswg-drafts/#8174](https://github.com/w3c/csswg-drafts/issues/8174).

**\[selectors\-4\] Add pseudo\-class to establish before\-change style for css\-transitions on new elements.**

* RESOLVED: specify \`@initial\` as defined in this issue and open another issue about the duplication problems with entry and exit styles
* RESOLVED: start with \`@starting\-style\` 

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8174#issuecomment-1515026543)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1834876
