### ISSUE TITLE
[css-ui] Consider removing slider-horizontal from <compat-auto>

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1114]
A resolution was made for [csswg-drafts/#8506](https://github.com/w3c/csswg-drafts/issues/8506).

**\[css\-ui\] Consider removing slider\-horizontal from &lt;compat\-auto&gt;**

* RESOLVED: remove slider\-horizontal, square\-button, and push\-button from &lt;compat\-auto&gt;; PaulG will open an issue about ARIA roles and concerns about slider\-vertical and push\-button

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8506#issuecomment-1515062326)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We already don't support these values, so no action needed.
