### ISSUE TITLE
[css-counter-styles-3] Should fallback use prefix/suffix of original style or fallback style?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1115]
A resolution was made for [csswg-drafts/#8619](https://github.com/w3c/csswg-drafts/issues/8619).

**\[css\-counter\-styles\-3\] Should fallback use prefix/suffix of original style or fallback style?**

* RESOLVED: No change to current spec. Draft ability for a counter function to return the counter string including prefix/suffix, with various fallback options

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8619#issuecomment-1523747123)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
In this case no-spec-change means we have some implementation work to do (or to revert). I filed I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1830127 on that.
