### ISSUE TITLE
[cssom-1] [css-cascade] CSSImportRule.sheet not being null conflicts with @import supports()

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1117]
A resolution was made for [csswg-drafts/#8608](https://github.com/w3c/csswg-drafts/issues/8608).

**\[cssom\-1\] \[css\-cascade\] CSSImportRule.sheet not being null conflicts with @import supports\(\)**

* RESOLVED: Update CSSOM to allow null representation of imported style sheets

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8608#issuecomment-1523758000)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by CanadaHonk** [comment]
No bug needed as this is already the case internally (was just non-compliant with spec :p)
