### ISSUE TITLE
[cssom-1] [css-cascade-4] Extend CSSImportRule to expose supports condition

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1118]
A resolution was made for [csswg-drafts/#8710](https://github.com/w3c/csswg-drafts/issues/8710).

**\[cssom\-1\] \[css\-cascade\-4\] Extend CSSImportRule to expose supports condition**

* RESOLVED: Accept IDL in issue

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8710#issuecomment-1523761524)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by CanadaHonk** [comment]
Bug already exists: https://bugzilla.mozilla.org/show_bug.cgi?id=1829590
