### ISSUE TITLE
[selectors-4] Add syntax to establish before-change style for css-transitions on new elements.

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1130]
A resolution was made for [csswg-drafts/#8174](https://github.com/w3c/csswg-drafts/issues/8174).

**\[selectors\-4\] Add syntax to establish before\-change style for css\-transitions on new elements.**

* RESOLVED: rename \`@initial\` to \`@starting\-style\` 

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8174#issuecomment-1561484749)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
Tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1834876
