### ISSUE TITLE
[css-values-4][css-color] Addition of `<color>` is way underspecified.

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1133]
A resolution was made for [csswg-drafts/#8576](https://github.com/w3c/csswg-drafts/issues/8576).

**\[css\-values\-4\]\[css\-color\] Addition of \`&lt;color&gt;\` is way underspecified.**

* RESOLVED: Colors don’t add; add a note asking for use cases and a warning specifying we might change in the future

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8576#issuecomment-1570575637)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
@BorisChiou do you know if we need a bug for this?  I'm not sure if we support the relevant animation features that would let us trigger this sort of addition yet.

**Comment by dholbert** [comment]
(side note, there are some github-comments after the resolution, which I can imagine might result in further refinements/discussion.)

**Comment by BorisChiou** [comment]
I guess we may need one bug for this. It seems we support all kinds of procedure (i.e. interpolation, addition, Accumulate):
https://searchfox.org/mozilla-central/rev/daedd554ae8a2c7f420ad77311134c8c298ba318/servo/components/style/values/animated/color.rs#58-72

Tiaan may know more about the current implementation about `<color>`

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1836160
