### ISSUE TITLE
[css-color-5] Examples 11, 20, 24, ... mix deg and number values

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1135]
A resolution was made for [csswg-drafts/#8839](https://github.com/w3c/csswg-drafts/issues/8839).

**\[css\-color\-5\] Examples 11, 20, 24, ... mix deg and number values**

* RESOLVED: keywords with multiple specified types result in number

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8839#issuecomment-1573767801)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
This was spawned by an issue quoting an earlier resolution.  We have https://github.com/mozilla/wg-decisions/issues/1001 for that resolution.
