### ISSUE TITLE
[css-transitions-2] Put discrete transitions behind new syntax for compatibility

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1137]
A resolution was made for [csswg-drafts/#8857](https://github.com/w3c/csswg-drafts/issues/8857).

**\[css\-transitions\-2\] Put discrete transitions behind new syntax for compatibility**

* RESOLVED: Pick option 2 with name to be bikeshed

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8857#issuecomment-1581650809)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
I think we can reuse https://bugzilla.mozilla.org/show_bug.cgi?id=1805727
