### ISSUE TITLE
[css-anchor-position-1] Request for FPWD

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1141]
A resolution was made for [csswg-drafts/#8929](https://github.com/w3c/csswg-drafts/issues/8929).

**\[css\-anchor\-position\-1\] Request for FPWD**

* RESOLVED: FPWD of css\-anchor\-positioning

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8929#issuecomment-1591593743)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1838746 to track implementation of the feature.
