### ISSUE TITLE
[css-grid-1] Behavior of an item spanning several auto minimum tracks

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1174]
A resolution was made for [csswg-drafts/#9075](https://github.com/w3c/csswg-drafts/issues/9075).

**\[css\-grid\-1\] Behavior of an item spanning several auto minimum tracks**

* RESOLVED: close no change and add tests

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9075#issuecomment-1641043536)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
In this one, our behavior is correct. No bug needed.

**Comment by dholbert** [comment]
(The thing that Tab noted is weird in Firefox is covered by https://github.com/mozilla/wg-decisions/issues/1175 )
