### ISSUE TITLE
[css-grid-2] Honoring the specified width/height of a subgrid

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1177]
A resolution was made for [csswg-drafts/#8966](https://github.com/w3c/csswg-drafts/issues/8966).

**\[css\-grid\-2\] Honoring the specified width/height of a subgrid**

* RESOLVED: close no change. spec is what we intended. action to file bugs on browsers and create WPTs

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8966#issuecomment-1641075674)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1844198 .
