### ISSUE TITLE
[css-transitions-2] Put discrete transitions behind new syntax for compatibility

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1196]
A resolution was made for [csswg-drafts/#8857](https://github.com/w3c/csswg-drafts/issues/8857).

**\[css\-transitions\-2\] Put discrete transitions behind new syntax for compatibility**

* RESOLVED: Add transition\-behavior longhand, list valued part of transition shorthand, with normal &124; allow\-discrete values \(to start\).

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8857#issuecomment-1646035541)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1805727
