### ISSUE TITLE
[css-animations-2] Make animation shorthand syntax future-proof

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1197]
A resolution was made for [csswg-drafts/#6946](https://github.com/w3c/csswg-drafts/issues/6946).

**\[css\-animations\-2\] Make animation shorthand syntax future\-proof**

* RESOLVED: Add a new syntax for the animation shorthand where the animation\-name comes first, followed by a slash, so that the new syntax \(but not the old one\) can accept animation\-timeline and animation\-composition in the shorthand.  Work out further details in issue.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6946#issuecomment-1646065211)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1824261
