### ISSUE TITLE
[css-transforms-2] Syntax of individual transforms should reflect general CSS syntax

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1201]
A resolution was made for [csswg-drafts/#7646](https://github.com/w3c/csswg-drafts/issues/7646).

**\[css\-transforms\-2\] Syntax of individual transforms should reflect general CSS syntax**

* RESOLVED: undo previous resolution, do not add the longhands to the rotate, translate, and scale properties

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7646#issuecomment-1646221413)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1856521
