### ISSUE TITLE
[css-anchor-1][css-position] Add the “centering” behavior which is now defined as an example in the specs as something built-in

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1205]
A resolution was made for [csswg-drafts/#8979](https://github.com/w3c/csswg-drafts/issues/8979).

**\[css\-anchor\-1\]\[css\-position\] Add the “centering” behavior which is now defined as an example in the specs as something built\-in**

* RESOLVED: add the anchor\-center value

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8979#issuecomment-1663086600)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
This is just to be implemented as part of anchor positioning, https://bugzilla.mozilla.org/show_bug.cgi?id=1838746
