### ISSUE TITLE
[css-shapes-1] Optional values shouldn't be serialized

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1209]
Resolutions were made for [csswg-drafts/#8695](https://github.com/w3c/csswg-drafts/issues/8695).

**\[css\-shapes\-1\] Optional values shouldn't be serialized**

* RESOLVED: We fix the example and tests based on it
* RESOLVED: Remove the part about serializing calc expressions from Shapes spec

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8695#issuecomment-1663106330)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1837340
