### ISSUE TITLE
[css-fonts] should supported tech() be validated during parsing or loading?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1221]
A resolution was made for [csswg-drafts/#8793](https://github.com/w3c/csswg-drafts/issues/8793).

**\[css\-fonts\] should supported tech\(\) be validated during parsing or loading?**

* RESOLVED: Make edits outlined by Chris

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8793#issuecomment-1680923925)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
@jfkthame do we need a bug for any Firefox changes related to this? I see you were involved in the discussion on #8793 .  (I skimmed quickly and wasn't immediately sure whether the spec edits might represent a change in behavior for us or not.)

**Comment by jfkthame** [comment]
This matches our existing behavior, so no changes needed.
