### ISSUE TITLE
[css-anchor-position-1] Allow more properties in position fallbacks

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1226]
A resolution was made for [csswg-drafts/#9195](https://github.com/w3c/csswg-drafts/issues/9195).

**\[css\-anchor\-position\-1\] Allow more properties in position fallbacks**

* RESOLVED: add border, padding, and margin properties to position fallback rules

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9195#issuecomment-1690141172)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
We don't implement this yet --> no bug needed for specific spec-changes at this point.
Our metabug is https://bugzilla.mozilla.org/show_bug.cgi?id=1838746
