### ISSUE TITLE
[css-anchor-position-1] Grid-based anchoring syntax?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1228]
Resolutions were made for [csswg-drafts/#9145](https://github.com/w3c/csswg-drafts/issues/9145).

**\[css\-anchor\-position\-1\] Grid\-based anchoring syntax?**

* RESOLVED: add a separate property \(can bikeshed name in future\), not merely a shorthand, but interacts with inset properties in current draft
* RESOLVED: inset\-area causes 'auto' keywords of inset to resolve to appropriate anchor\(\) functions \(TBD at computed or used value time\)

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9145#issuecomment-1690207503)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
We don't implement this yet --> no bug needed for specific spec-changes at this point.
Our metabug is https://bugzilla.mozilla.org/show_bug.cgi?id=1838746
