### ISSUE TITLE
[css-inline-3] It's impossible to use `text-box-trim` without changing line progression within the paragraph

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1236]
A resolution was made for [csswg-drafts/#8829](https://github.com/w3c/csswg-drafts/issues/8829).

**\[css\-inline\-3\] It's impossible to use \`text\-box\-trim\` without changing line progression within the paragraph**

* RESOLVED: Three longhand properties as proposed with two linked by a shorthand, names to be bikeshed, one issue for each to work them out

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8829#issuecomment-1699500216)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't implement this feature yet; this is https://bugzilla.mozilla.org/show_bug.cgi?id=1816038
