### ISSUE TITLE
[css-contain][css-anchor-position] Anchor names should be contained by style containment

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1241]
A resolution was made for [csswg-drafts/#9100](https://github.com/w3c/csswg-drafts/issues/9100).

**\[css\-contain\]\[css\-anchor\-position\] Anchor names should be contained by style containment**

* RESOLVED: Style containment contains anchor names

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9100#issuecomment-1704331078)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
We don't implement this yet --> no bug needed for specific spec-changes at this point.
Our metabug is https://bugzilla.mozilla.org/show_bug.cgi?id=1838746
