### ISSUE TITLE
[css-pseudo-4] Support for highlight pseudos declarations inside @container media queries

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1245]
A resolution was made for [csswg-drafts/#9280](https://github.com/w3c/csswg-drafts/issues/9280).

**\[css\-pseudo\-4\] Support for highlight pseudos declarations inside @container media queries**

* RESOLVED: Disallow the use inside container blocks

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9280#issuecomment-1709271978)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't support highlight pseudos at all; those are tracked in bug https://bugzilla.mozilla.org/show_bug.cgi?id=1703963

So: no action for us from this resolution.
