### ISSUE TITLE
[css-contain-2] Should CSS highlights make content relevant to the user?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1246]
A resolution was made for [csswg-drafts/#9277](https://github.com/w3c/csswg-drafts/issues/9277).

**\[css\-contain\-2\] Should CSS highlights make content relevant to the user?**

* RESOLVED: Change the line about selection to link to the selection API instead of highlight pseudo element

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9277#issuecomment-1709275534)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
This might need a bug.  Previously the reference to highlight pseudos would've been irrelevant for us (for now) since we don't support those per https://bugzilla.mozilla.org/show_bug.cgi?id=1703963 . But we do support the selection API that the spec is now referencing.

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1852199

**Comment by dholbert** [comment]
This doesn't need any changes from us after all, as noted in the bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1852199#c2

(the spec change is just grounding things in a better definition of what selection is, and we were already checking for selections as part of this code, in a way that's not impacted by the spec clarification).
