### ISSUE TITLE
[css-anchor-position-1] Better reusability of anchor names

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1262]
A resolution was made for [csswg-drafts/#9045](https://github.com/w3c/csswg-drafts/issues/9045).

**\[css\-anchor\-position\-1\] Better reusability of anchor names**

* RESOLVED: Add an \`anchor\-scope\` property

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9045#issuecomment-1721297734)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
We don't implement this yet --> no bug needed for specific spec-changes at this point.
Our metabug is https://bugzilla.mozilla.org/show_bug.cgi?id=1838746
