### ISSUE TITLE
[css-anchor-position-1] Define interaction with the cascade in `@try`

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1263]
A resolution was made for [csswg-drafts/#9149](https://github.com/w3c/csswg-drafts/issues/9149).

**\[css\-anchor\-position\-1\] Define interaction with the cascade in \`@try\`**

* RESOLVED: !important must win and the issue of putting @try properties in their place in the cascade will be investigated

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9149#issuecomment-1721333819)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
We don't implement this yet --> no bug needed for specific spec-changes at this point.
Our metabug is https://bugzilla.mozilla.org/show_bug.cgi?id=1838746
