### ISSUE TITLE
[css-view-transitions-1] Animate backdrop-filter for named elements

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1271]
A resolution was made for [csswg-drafts/#9358](https://github.com/w3c/csswg-drafts/issues/9358).

**\[css\-view\-transitions\-1\] Animate backdrop\-filter for named elements**

* RESOLVED: animate backdrop\-filter for view transitions similar to transform/size

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9358#issuecomment-1737718423)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't implement view transitions yet.
