### ISSUE TITLE
[css-cascade] [css-nesting] Figure out whether we're fine with "shifting up" bare declarations after rules

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1286]
A resolution was made for [csswg-drafts/#8738](https://github.com/w3c/csswg-drafts/issues/8738).

**\[css\-cascade\] \[css\-nesting\] Figure out whether we're fine with "shifting up" bare declarations after rules**

* RESOLVED: We will address ths issue, and fix nesting to allow for bare declarations after nested rules without moving them above.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8738#issuecomment-1768977689)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
IIUC, there's no-change for us at this point, though @emilio please file a bug if there's already a concrete change we should make here. Thanks!

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1859915
