### ISSUE TITLE
[css-scroll-snap-1] Improve or clarify nested snap behaviors

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1304]
A resolution was made for [csswg-drafts/#9187](https://github.com/w3c/csswg-drafts/issues/9187).

**\[css\-scroll\-snap\-1\] Improve or clarify nested snap behaviors**

* RESOLVED: Better define this behavior when you have nested snap areas and children with interleaved content from the parent

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9187#issuecomment-1812985915)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
CC @hiikezoe, as a heads-up about this forthcoming scroll-snap spec-change.  (I won't have mozilla-apprentice file a bug right now since the spec change isn't concrete yet I think; but presumably we'll need a bug at some point once the new behavior is defined.)

**Comment by hiikezoe** [comment]
Thanks Daniel. I am assuming this spec change will be a part of Interop 2024 scrolling focus area, see [this comment](https://github.com/web-platform-tests/interop/issues/471#issuecomment-1759542740) in the carry over discussion.  We will file a new in the next year.
