### ISSUE TITLE
[css-values] Abandon mix()?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1316]
Resolutions were made for [csswg-drafts/#9343](https://github.com/w3c/csswg-drafts/issues/9343).

**\[css\-values\] Abandon mix\(\)?**

* RESOLVED: Drop mix\(\) from Values 4
* RESOLVED: we will never use mix to represent a single interpolated value but may have something like it for expressing the whole interpolation

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9343#issuecomment-1843933577)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
AFAIK this isn't something we implement, so dropping it from the spec is no-change for us.
