### ISSUE TITLE
[css-page3] [cssom] Descriptors and properties

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1320]
Resolutions were made for [csswg-drafts/#9685](https://github.com/w3c/csswg-drafts/issues/9685).

**\[css\-page3\] \[cssom\] Descriptors and properties**

* RESOLVED: Having different interfaces for declarations blocks that expose a different set of descriptors/properties
* RESOLVED: Go with emilio naming and Sam's amendment

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9685#issuecomment-1846657195)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by cdoublev** [comment]
No resolution were made. I cited a resolution, which triggered this report. Sorry about that.

**Comment by dholbert** [comment]
No worries! Sorry the bot is spammy. :)
