### ISSUE TITLE
[css-fonts-4] font-stretch is unfortunately named

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1349]
A resolution was made for [csswg-drafts/#551](https://github.com/w3c/csswg-drafts/issues/551).

**\[css\-fonts\-4\] font\-stretch is unfortunately named**

* RESOLVED: Add font\-width property and descriptor and make font\-stretch a legacy alias

[Discussion.](https://github.com/w3c/csswg-drafts/issues/551#issuecomment-1885196273)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1911075
