### ISSUE TITLE
[css-overflow-4] line-clamp `max-lines` - support `auto` value to fit container 

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1354]
A resolution was made for [csswg-drafts/#9368](https://github.com/w3c/csswg-drafts/issues/9368).

**\[css\-overflow\-4\] line\-clamp \`max\-lines\` \- support \`auto\` value to fit container **

* RESOLVED: Change the line\-clamp shorthand syntax to allow omitting the max\-lines value

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9368#issuecomment-1892927113)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
No action needed; we don't support `max-lines` yet, per:
https://searchfox.org/mozilla-central/rev/2fa4750e87d49ec7ad19fa1da167a03ef6d5e954/servo/components/style/values/generics/box.rs#128-132
```rust
/// Note that we only implement -webkit-line-clamp as a single, longhand
/// property for now, but the spec defines line-clamp as a shorthand for
/// separate max-lines, block-ellipsis, and continue properties.
///
/// https://drafts.csswg.org/css-overflow-3/#line-clamp
```
