### ISSUE TITLE
Proposal: Custom CSS Functions & Mixins

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1382]
A resolution was made for [csswg-drafts/#9350](https://github.com/w3c/csswg-drafts/issues/9350).

**Proposal: Custom CSS Functions &amp; Mixins**

* RESOLVED: Start ED of css\-mixins for CSS Custom Functions and Mixins

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9350#issuecomment-1939628591)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
Nothing concrete to implement yet --> no bug at this point.
