### ISSUE TITLE
[css-inline-3] Negative margins on inline boxes

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1388]
A resolution was made for [csswg-drafts/#8182](https://github.com/w3c/csswg-drafts/issues/8182).

**\[css\-inline\-3\] Negative margins on inline boxes**

* RESOLVED: we have fantasai start speccing accumulating neg margins for inline boxes

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8182#issuecomment-1940000516)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
Looks like there's nothing implementable yet; we can file a bug once fantasai's got spec text written that we can implement.
