### ISSUE TITLE
[css-anchor-1] Preserve the previously used fallback position when all fallbacks fail

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1390]
Resolutions were made for [csswg-drafts/#8200](https://github.com/w3c/csswg-drafts/issues/8200).

**\[css\-anchor\-1\] Preserve the previously used fallback position when all fallbacks fail**

* RESOLVED: Modulo timing details and things that should cause us to forget, the last successful fallback position is used when all options fail
* RESOLVED: If there's no previously successful fallback, we'll use the base styles with no fallback rules applied

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8200#issuecomment-1942271377)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't implement this yet --> no bug needed for specific spec-changes at this point.
Our metabug is https://bugzilla.mozilla.org/show_bug.cgi?id=1838746
