### ISSUE TITLE
[css-anchor-position-1] `position-fallback-bounds` vs `position-container`

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1392]
A resolution was made for [csswg-drafts/#9868](https://github.com/w3c/csswg-drafts/issues/9868).

**\[css\-anchor\-position\-1\] \`position\-fallback\-bounds\` vs \`position\-container\`**

* RESOLVED: Replace position\-fallback\-bounds with a more generic solution that addresses positioning and not just overflow checks

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9868#issuecomment-1942383523)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't implement this yet --> no bug needed for specific spec-changes at this point.
Our metabug is https://bugzilla.mozilla.org/show_bug.cgi?id=1838746
