### ISSUE TITLE
improve styling of <details>/<summary> elements

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1393]
Resolutions were made for [csswg-drafts/#9879](https://github.com/w3c/csswg-drafts/issues/9879).

**improve styling of &lt;details&gt;/&lt;summary&gt; elements**

* RESOLVED: Expose the &lt;details&gt; contents slot as either a pseudo or a ::part, as decided in a joint meeting with WHATWG
* RESOLVED: We desire to have no restrictions on the stylability of the display of &lt;details&gt; and &lt;summary&gt;

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9879#issuecomment-1942785500)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
Nothing concrete to implement yet --> no bug at this point.
