### ISSUE TITLE
[css-transforms-1] The computed value of `transform` if the transformed element is display:none

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1397]
A resolution was made for [csswg-drafts/#9121](https://github.com/w3c/csswg-drafts/issues/9121).

**\[css\-transforms\-1\] The computed value of \`transform\` if the transformed element is display:none**

* RESOLVED: non\-transformable elements and elements without a box return a matrix\(\) resolved against a 0x0 box

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9121#issuecomment-1942886970)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
@emilio double-checking: I think the resolved-upon behavior matches our existing behavior and we don't need a bug, right?

**Comment by emilio** [comment]
It's not our behavior for inlines / table parts.

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1880195
