### ISSUE TITLE
[css-borders] accept "px" for pixel values in `border-image-slice`

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1412]
A resolution was made for [csswg-drafts/#6739](https://github.com/w3c/csswg-drafts/issues/6739).

**\[css\-borders\] accept "px" for pixel values in \`border\-image\-slice\`**

* RESOLVED: Not going to use the pixel unit for the pixel value in border\-image\-slice

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6739#issuecomment-1969530684)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
As I understand it, this resolution was "close no-change", so no bug needed.
