### ISSUE TITLE
Can we reinstate `<number-percentage>` and friends?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1416]
A resolution was made for [csswg-drafts/#9955](https://github.com/w3c/csswg-drafts/issues/9955).

**Can we reinstate \`&lt;number\-percentage&gt;\` and friends?**

* RESOLVED: % that are resolved against numbers do that at parse time

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9955#issuecomment-1974857567)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by cdoublev** [comment]
You can close this issue. No new resolution was made. I just mentioned a resolution.
