### ISSUE TITLE
[css-anchor-position] Rename `anchor-default` to `position-anchor`

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1425]
A resolution was made for [csswg-drafts/#10004](https://github.com/w3c/csswg-drafts/issues/10004).

**\[css\-anchor\-position\] Rename \`anchor\-default\` to \`position\-anchor\`**

* RESOLVED: rename anchor\-default to position\-anchor

[Discussion.](https://github.com/w3c/csswg-drafts/issues/10004#issuecomment-1994624254)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
We don't implement this yet --> no bug needed for specific spec-changes at this point.
Our metabug is https://bugzilla.mozilla.org/show_bug.cgi?id=1838746
