### ISSUE TITLE
[css-anchor-1] Need ability to say "don't render" when anchor is off-screen

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1426]
A resolution was made for [csswg-drafts/#7758](https://github.com/w3c/csswg-drafts/issues/7758).

**\[css\-anchor\-1\] Need ability to say "don't render" when anchor is off\-screen**

* RESOLVED:  Add position\-visibility as proposed in the issue with concerns noted as issues in the draft, to the editors draft \*after\* publication of working draft.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7758#issuecomment-1994765991)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
We don't implement this yet --> no bug needed for specific spec-changes at this point.
Our metabug is https://bugzilla.mozilla.org/show_bug.cgi?id=1838746
