### ISSUE TITLE
[css-grid][css-flexbox] Blockification section should use the computed value, not the box of the element

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#143]
A resolution was made for [csswg-drafts/#4065](https://github.com/w3c/csswg-drafts/issues/4065).

**\[css\-grid\]\[css\-flexbox\] Blockification section should use the computed value, not the box of the element**

* RESOLVED: Accept edit in https://github.com/w3c/csswg\-drafts/issues/4065

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4065#issuecomment-556164168)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
No action needed.
