### ISSUE TITLE
[css-transforms-2] The readiness of shipping individual transform properties - translate, rotate, scale

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#145]
Resolutions were made for [csswg-drafts/#4515](https://github.com/w3c/csswg-drafts/issues/4515).

**\[css\-transforms\-2\] The readiness of shipping individual transform properties \- translate, rotate, scale**

* RESOLVED: Working group is fine with translate, rotate and scale shipping
* RESOLVED: Move the 3D transforms to a level 3of Transforms

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4515#issuecomment-556175448)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
This is for https://bugzilla.mozilla.org/show_bug.cgi?id=1424900.
