### ISSUE TITLE
[css-images-4] Should `contain-intrinsic-size` affect `object-fit`?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1451]
A resolution was made for [csswg-drafts/#10116](https://github.com/w3c/csswg-drafts/issues/10116).

**\[css\-images\-4\] Should \`contain\-intrinsic\-size\` affect \`object\-fit\`?**

* RESOLVED: \`contain\` removes the natural aspect ratio / width / height only for the purposes of sizing and layout of the box \(and object\-fit is therefore not affected\)

[Discussion.](https://github.com/w3c/csswg-drafts/issues/10116#issuecomment-2035803916)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
No bug needed; this is covered by https://bugzilla.mozilla.org/show_bug.cgi?id=1886745 .
