### ISSUE TITLE
[css-scrollbars] Interaction between scrollbar-color and scrollbar-width with ::-webkit-scrollbar

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1452]
A resolution was made for [csswg-drafts/#9856](https://github.com/w3c/csswg-drafts/issues/9856).

**\[css\-scrollbars\] Interaction between scrollbar\-color and scrollbar\-width with ::\-webkit\-scrollbar**

* RESOLVED: If either scrollbar\-width or scrollbar\-color are anything other than initial values, then we ignore legacy \-webkit\-scroll pseudos

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9856#issuecomment-2035809422)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
This doesn't impact us, since we don't support `webkit-scrollbar` pseudos.
