### ISSUE TITLE
[css-text-4] Rename `trim-auto` to `trim-both`

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1455]
A resolution was made for [csswg-drafts/#10161](https://github.com/w3c/csswg-drafts/issues/10161).

**\[css\-text\-4\] Rename \`trim\-auto\` to \`trim\-both\`**

* RESOLVED: rename trim\-auto to trim\-both

[Discussion.](https://github.com/w3c/csswg-drafts/issues/10161#issuecomment-2048015797)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
This is a change to `text-spacing-trim` which I don't think we implement yet, so no bug needed for this change.
