### ISSUE TITLE
[css-cascade] [css-nesting] Figure out whether we're fine with "shifting up" bare declarations after rules

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1458]
A resolution was made for [csswg-drafts/#8738](https://github.com/w3c/csswg-drafts/issues/8738).

**\[css\-cascade\] \[css\-nesting\] Figure out whether we're fine with "shifting up" bare declarations after rules**

* RESOLVED: Tab specs @nest, with a note about user\-facing stuff being something we might want to get rid of

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8738#issuecomment-2061777236)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
no spec text yet, so probably no bug merited yet (though @emilio free free to reopen this and add 'bug' label to get a placeholder bug if you think it's appropriate).
