### ISSUE TITLE
[css-ruby-1] Breaks within implicit bases is not Web-compatible

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1463]
Resolutions were made for [csswg-drafts/#10073](https://github.com/w3c/csswg-drafts/issues/10073).

**\[css\-ruby\-1\] Breaks within implicit bases is not Web\-compatible**

* RESOLVED: Style anonymous bases with text\-wrap\-mode: nowrap as described in https://github.com/w3c/csswg\-drafts/issues/10073\#issuecomment\-1995455391
* RESOLVED: unresolve previous resolution

[Discussion.](https://github.com/w3c/csswg-drafts/issues/10073#issuecomment-2075297324)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1893239

**Comment by dholbert** [comment]
er, my bad; I mistook "unresolve previous resolution" to be referring to some older resolution, and that the first resolution here was still actionable.

Looks like this is still TBD what we're gonna do, and there's nothing actionable yet.
