### ISSUE TITLE
[css-pseudo-4] painting order of find-in-page highlights

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1469]
A resolution was made for [csswg-drafts/#10213](https://github.com/w3c/csswg-drafts/issues/10213).

**\[css\-pseudo\-4\] painting order of find\-in\-page highlights**

* RESOLVED: ::search\-text paints directly above or directly below ::selection \(up to UA\)

[Discussion.](https://github.com/w3c/csswg-drafts/issues/10213#issuecomment-2089311110)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
This matches our existing find-in-page behavior, as discussed in the meeting.
