### ISSUE TITLE
[css-anchor-position] `position-anchor` should be defined as a longhand of `position`

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1475]
A resolution was made for [csswg-drafts/#10321](https://github.com/w3c/csswg-drafts/issues/10321).

**\[css\-anchor\-position\] \`position\-anchor\` should be defined as a longhand of \`position\`**

* RESOLVED: Make position a shorthand of position\-anchor and a new position\-type property. The shorthand resets both.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/10321#issuecomment-2112965730)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
FYI @jwatt
