### ISSUE TITLE
[css-anchor-position] Initial value of `position-anchor` should be `auto` not `implicit`

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1478]
Resolutions were made for [csswg-drafts/#10312](https://github.com/w3c/csswg-drafts/issues/10312).

**\[css\-anchor\-position\] Initial value of \`position\-anchor\` should be \`auto\` not \`implicit\`**

* RESOLVED: Rename implicit to auto in position\-anchor
* RESOLVED: Drop the keyword from the anchor\(\) function

[Discussion.](https://github.com/w3c/csswg-drafts/issues/10312#issuecomment-2112984254)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
no bug needed (but @jwatt, FYI regarding a syntax change here)
