### ISSUE TITLE
[css-anchor-position] Default alignments for inset areas are wrong

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1479]
A resolution was made for [csswg-drafts/#10313](https://github.com/w3c/csswg-drafts/issues/10313).

**\[css\-anchor\-position\] Default alignments for inset areas are wrong**

* RESOLVED: If inset\-area spans both of the tracks we'll align toward the missing track instead of centering

[Discussion.](https://github.com/w3c/csswg-drafts/issues/10313#issuecomment-2112996339)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
I imagine this'll make it into the spec soon, but fyi @jwatt just in case he's implementing this behavior before the spec is updated.
