### ISSUE TITLE
[css-viewport] Add a meta viewport parameter to control ICB layout behavior for interactive overlays

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1482]
A resolution was made for [csswg-drafts/#7767](https://github.com/w3c/csswg-drafts/issues/7767).

**\[css\-viewport\] Add a meta viewport parameter to control ICB layout behavior for interactive overlays**

* RESOLVED: Leave open, bring back in the upcoming F2F

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7767#issuecomment-2125261357)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by theres-waldo** [comment]
This has been implemented in Firefox in https://bugzilla.mozilla.org/show_bug.cgi?id=1831649.
