### ISSUE TITLE
[css-flexbox] Change content-size suggestion to min-intrinsic instead of min-content?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1483]
A resolution was made for [csswg-drafts/#6794](https://github.com/w3c/csswg-drafts/issues/6794).

**\[css\-flexbox\] Change content\-size suggestion to min\-intrinsic instead of min\-content?**

* RESOLVED: change minimum size of flex items to be the larger of min\-intrinsic and transferred size

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6794#issuecomment-2125293490)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
No immediate change on our side; this change is to make the spec (and Chromium who implemented the spec text) align more closely with Firefox and WebKit.

Ian did mention that Firefox and WebKit aren't internally consistent, but we can file bugs as those specific cases are determined (possibly by the WPT tests he'll be adding as part of this change).
