### ISSUE TITLE
[css-pseudo] Which properties to reset in ::marker

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#149]
A resolution was made for [csswg-drafts/#4568](https://github.com/w3c/csswg-drafts/issues/4568).

**\[css\-pseudo\] Which properties to reset in ::marker**

* RESOLVED: marker exists on all elements, on ::before and on ::after but no box unless it's display: list\-item

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4568#issuecomment-564484838)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by Loirooriol** [comment]
I was just quoting a previous resolution from another issue, you can close this

**Comment by emilio** [comment]
Yup, thanks oriol.
