### ISSUE TITLE
[css-overflow] Top layer containing block and scrollbar-gutter

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1504]
A resolution was made for [csswg-drafts/#9904](https://github.com/w3c/csswg-drafts/issues/9904).

**\[css\-overflow\] Top layer containing block and scrollbar\-gutter**

* RESOLVED: \(top layer or fullscreen\) elements with 'position: fixed' cover the scrollbars/gutters

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9904#issuecomment-2161022451)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
We can fix this issue in https://bugzilla.mozilla.org/show_bug.cgi?id=1874091
