### ISSUE TITLE
[view-transitions-2] Add method to get all animations of a ViewTransition object

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1537]
Resolutions were made for [csswg-drafts/#9908](https://github.com/w3c/csswg-drafts/issues/9908).

**\[view\-transitions\-2\] Add method to get all animations of a ViewTransition object**

* RESOLVED: Add a pseudoElement option to the element.getAnimations\(\) dict arg. subtree:true/false acts on that pseudo as the root
* RESOLVED: Add .transitionRoot readonly property to VT object, reflectring the element hosting the VT.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9908#issuecomment-2165621635)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1935557

**Comment by BorisChiou** [comment]
We need a bug for web-animations change, i.e. add pseudoElement in getAnimations(), though this is for web-animations level 1.
