### ISSUE TITLE
[css-anchor-position] Rename `position-try-options` to `position-try-fallbacks`

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1546]
A resolution was made for [csswg-drafts/#10395](https://github.com/w3c/csswg-drafts/issues/10395).

**\[css\-anchor\-position\] Rename \`position\-try\-options\` to \`position\-try\-fallbacks\`**

* RESOLVED: rename position\-try\-options to position\-try\-fallbacks

[Discussion.](https://github.com/w3c/csswg-drafts/issues/10395#issuecomment-2192127524)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
CC @jwatt

(No bug needed since we haven't landed support for this property yet --> closing)
