### ISSUE TITLE
[css-anchor-position-1] Bikeshed name of `inset-area`

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1559]
A resolution was made for [csswg-drafts/#10209](https://github.com/w3c/csswg-drafts/issues/10209).

**\[css\-anchor\-position\-1\] Bikeshed name of \`inset\-area\`**

* RESOLVED: Change inset\-area back to position\-area

[Discussion.](https://github.com/w3c/csswg-drafts/issues/10209#issuecomment-2221005001)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by nt1m** [comment]
cc @jwatt

**Comment by aethanyc** [comment]
Firefox hasn't implemented anchor-position yet. I believe there is nothing to change it the code.

**Comment by nt1m** [comment]
@aethanyc `inset-area` parsing was implemented: https://bugzilla.mozilla.org/show_bug.cgi?id=1898887, that probably needs updating to be `position-area`

**Comment by aethanyc** [comment]
@nt1m you're right. Firefox has implemented `inset-area`. https://bugzilla.mozilla.org/show_bug.cgi?id=1909358 will cover this rename.
