### ISSUE TITLE
[css-font-loading] Remove the FontFaceSet constructor?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1567]
A resolution was made for [csswg-drafts/#10390](https://github.com/w3c/csswg-drafts/issues/10390).

**\[css\-font\-loading\] Remove the FontFaceSet constructor?**

* RESOLVED: Delete FontFaceSet constructor from the spec

[Discussion.](https://github.com/w3c/csswg-drafts/issues/10390#issuecomment-2233736229)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
Based on the initial comment on https://github.com/w3c/csswg-drafts/issues/10390 and a later comment from @emilio, only Safari has the constructor (that we've now resolved to remove), so this is no-change on our side.
