### ISSUE TITLE
[css-shapes] Clarify which `<basic-shape>` are valid in `shape-*`

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1577]
Resolutions were made for [csswg-drafts/#9728](https://github.com/w3c/csswg-drafts/issues/9728).

**\[css\-shapes\] Clarify which \`&lt;basic\-shape&gt;\` are valid in \`shape\-\*\`**

* RESOLVED: Shapes Level 1 is modified to say that shape\-outside takes all &lt;basic\-shape&gt;s
* RESOLVED: Publish a new CRD of Shapes 1 with this change \(and whatever else is already in since last publication\)

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9728#issuecomment-2260954580)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
No implementation change needed.
