### ISSUE TITLE
[css-overflow-4] When does the blockification of -webkit-box occur?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1598]
A resolution was made for [csswg-drafts/#10435](https://github.com/w3c/csswg-drafts/issues/10435).

**\[css\-overflow\-4\] When does the blockification of \-webkit\-box occur?**

* RESOLVED: blockification of \-webkit\-box happens at computed value time

[Discussion.](https://github.com/w3c/csswg-drafts/issues/10435#issuecomment-2315852881)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
@emilio Do we need to change our implementation to match the resolution?

**Comment by emilio** [comment]
No, we resolved in our behavior.
