### ISSUE TITLE
[css-anchor-position] `position-anchor` should be defined as a longhand of `position`

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1600]
A resolution was made for [csswg-drafts/#10321](https://github.com/w3c/csswg-drafts/issues/10321).

**\[css\-anchor\-position\] \`position\-anchor\` should be defined as a longhand of \`position\`**

* RESOLVED: undo the previous resolution and not add position\-anchor and position\-type to the position shorthand for now

[Discussion.](https://github.com/w3c/csswg-drafts/issues/10321#issuecomment-2330338181)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
CC @jwatt @dshin-moz -- I don't think we've gone to the trouble of making `position` a shorthand yet so I think there's nothing for us to do here.

The "previous resolution" here had been:
> Make `position` a shorthand of `position-anchor` and a new `position-type` property. The shorthand resets both.

We didn't do that yet (fortunately) and now we've undone that resolution, as discussed in the csswg-drafts issue, so no bug is needed.

**Comment by dholbert** [comment]
(Just for record-keeping, we had #1475 on the previous resolution; we didn't bother with a bug there since it happened before we'd gotten started with the anchor parsing stuff in general. So no bug cleanup needed for undoing the resolution.)
