### ISSUE TITLE
[css-inline] Disallow `auto` in `text-box` shorthand

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1607]
A resolution was made for [csswg-drafts/#10748](https://github.com/w3c/csswg-drafts/issues/10748).

**\[css\-inline\] Disallow \`auto\` in \`text\-box\` shorthand**

* RESOLVED: Drop the auto value in the text\-box shorthand

[Discussion.](https://github.com/w3c/csswg-drafts/issues/10748#issuecomment-2339319731)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't support this `text-box` shorthand property (this is part of `text-box-trim` which we also don't support[1]), so no change for us.

[1] https://caniuse.com/css-text-box-trim

**Comment by dholbert** [comment]
(for reference, https://bugzilla.mozilla.org/show_bug.cgi?id=1816038 is our bug on implementing `text-box-trim`.)
