### ISSUE TITLE
[css-scrollbars] Is the track visible in overlay scrollbars?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1609]
A resolution was made for [csswg-drafts/#9855](https://github.com/w3c/csswg-drafts/issues/9855).

**\[css\-scrollbars\] Is the track visible in overlay scrollbars?**

* RESOLVED: accept proposal as outlined in github, with an exception when the author explicitly sets a fully transparent track.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/9855#issuecomment-2344135117)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
The "proposal as outlined in github" is the spec text proposed here, I think:
https://github.com/w3c/csswg-drafts/issues/9855#issuecomment-2036006569

The requirement for us there is "If the user agent displays the scrollbar without the [=track=], they must ensure reasonable contrast between the [=thumb=] and what is behind it."

I think we need a bug for this; I'm finding cases where we don't do this right now.

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1918212
