### ISSUE TITLE
[css-view-transitions-2] view-transition-name determined by element 

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1610]
A resolution was made for [csswg-drafts/#8320](https://github.com/w3c/csswg-drafts/issues/8320).

**\[css\-view\-transitions\-2\] view\-transition\-name determined by element **

* RESOLVED: Add three keywords, one for ID attribute, one for element identity, and one that does fallback between the two.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8320#issuecomment-2344208387)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
CC @BorisChiou @emilio in case we need a bug for this (I'm not sure offhand)

**Comment by BorisChiou** [comment]
We probably need a bug to extend the value of `view-transition-name`.

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1918218
