### ISSUE TITLE
[css-view-transitions] Users need to be able to disable view transitions

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1619]
A resolution was made for [csswg-drafts/#10267](https://github.com/w3c/csswg-drafts/issues/10267).

**\[css\-view\-transitions\] Users need to be able to disable view transitions**

* RESOLVED: in cases of prefers\-reduced\-motion the UA stylesheet will define a cross\-fade animation by default, without size/position animation

[Discussion.](https://github.com/w3c/csswg-drafts/issues/10267#issuecomment-2369894361)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
We are still developing view transitions, and I expected we will handle this well in our existing bugs.
