### ISSUE TITLE
[css‑fonts‑4] Create keywords for `unicode‑range`

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1622]
Resolutions were made for [csswg-drafts/#4573](https://github.com/w3c/csswg-drafts/issues/4573).

**\[css‑fonts‑4\] Create keywords for \`unicode‑range\`**

* RESOLVED: Add a set of keywords from SCript and Script Extensions
* RESOLVED: Punting on General category for now.
* RESOLVED: script categories can be excluded \(except for Common\)

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4573#issuecomment-2372608901)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
@jfkthame I see a new bugzilla bug is filed in https://github.com/mozilla/wg-decisions/issues/204 for an older resolution in the spec issue. Do we need a bug for this newer resolution?

**Comment by jfkthame** [comment]
I don't think we need another bug; I just added a comment to point to the newer resolutions - thanks.
