### ISSUE TITLE
[css-values-4] Specify that calculation trees explicitly work in double precision

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#163]
A resolution was made for [csswg-drafts/#4551](https://github.com/w3c/csswg-drafts/issues/4551).

**\[css\-values\-4\] Specify that calculation trees explicitly work in double precision**

* RESOLVED: Math precision in CSS is currently kept undefined

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4551#issuecomment-577138376)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
Nothing to do.
