### ISSUE TITLE
[css-view-transitions-2] Nested transitions: what happens if there is a mismatch?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1633]
A resolution was made for [csswg-drafts/#10631](https://github.com/w3c/csswg-drafts/issues/10631).

**\[css\-view\-transitions\-2\] Nested transitions: what happens if there is a mismatch?**

* RESOLVED: Use Option 1 \(last capture wins\) when there's a v\-t\-group mismatch.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/10631#issuecomment-2377967046)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
Per the comment in the spec issue, this matches the spec wording by default.
