### ISSUE TITLE
[css-overflow-5] Bikeshed pseudoclasses for active scroll-marker

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1661]
A resolution was made for [csswg-drafts/#10918](https://github.com/w3c/csswg-drafts/issues/10918).

**\[css\-overflow\-5\] Bikeshed pseudoclasses for active scroll\-marker**

* RESOLVED: \`:current\` is better than \`:checked\`, issue remains open while we look for better alternatives

[Discussion.](https://github.com/w3c/csswg-drafts/issues/10918#issuecomment-2380329944)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
This is part of a feature we don't support yet, flackr's carousel proposal.
