### ISSUE TITLE
[css-inline] Is `text-box-edge` inherited or not?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1670]
A resolution was made for [csswg-drafts/#10904](https://github.com/w3c/csswg-drafts/issues/10904).

**\[css\-inline\] Is \`text\-box\-edge\` inherited or not?**

* RESOLVED: make property text\-box\-edge inherited

[Discussion.](https://github.com/w3c/csswg-drafts/issues/10904#issuecomment-2417297683)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't support `text-box-edge` yet. It's associated with https://bugzilla.mozilla.org/show_bug.cgi?id=1816038 (text-box-trim) I think.
