### ISSUE TITLE
[css-view-transitions] Users need to be able to disable view transitions

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1678]
A resolution was made for [csswg-drafts/#10267](https://github.com/w3c/csswg-drafts/issues/10267).

**\[css\-view\-transitions\] Users need to be able to disable view transitions**

* RESOLVED: in cases of prefers\-reduced\-motion the UA stylesheet will define a cross\-fade animation by default, without size/position animation

[Discussion.](https://github.com/w3c/csswg-drafts/issues/10267#issuecomment-2430533687)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
duplicated by https://github.com/mozilla/wg-decisions/issues/1619
