### ISSUE TITLE
[css-ui] Colors to use for appearance:base `<select>`

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1682]
A resolution was made for [csswg-drafts/#10909](https://github.com/w3c/csswg-drafts/issues/10909).

**\[css\-ui\] Colors to use for appearance:base \`&lt;select&gt;\`**

* RESOLVED: Adopt ::check or ::checkmark for checkbox/radio checks

[Discussion.](https://github.com/w3c/csswg-drafts/issues/10909#issuecomment-2435687231)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't implement `appearance:base` yet. Closing.
