### ISSUE TITLE
[css-animations] Proposal: Add a way to make the animation timing function apply to the whole animation

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1687]
A resolution was made for [csswg-drafts/#8881](https://github.com/w3c/csswg-drafts/issues/8881).

**\[css\-animations\] Proposal: Add a way to make the animation timing function apply to the whole animation**

* RESOLVED: add the 'animation\-easing' as defined in the issue, and add a new initial value for animation\-timing\-function to something that computes to ease or linear depending on animation\-easing

[Discussion.](https://github.com/w3c/csswg-drafts/issues/8881#issuecomment-2450234110)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
This is duplicated by https://github.com/mozilla/wg-decisions/issues/1635. We have a bug for it already.
