### ISSUE TITLE
[css-values-4][Editorial] `<condition>` type that other specs reference

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1689]
A resolution was made for [csswg-drafts/#10457](https://github.com/w3c/csswg-drafts/issues/10457).

**\[css\-values\-4\]\[Editorial\] \`&lt;condition&gt;\` type that other specs reference**

* RESOLVED: Add &lt;boolean\-expr\[...\]&gt; as a value definition syntax function multiplying its argument into a boolean expression microsyntax

[Discussion.](https://github.com/w3c/csswg-drafts/issues/10457#issuecomment-2461076362)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
This was just some spec syntactic-sugar, with no functional change for us.
