### ISSUE TITLE
[css-backgrounds-4] default background-origin for `border-area` in shorthand

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1699]
A resolution was made for [csswg-drafts/#11167](https://github.com/w3c/csswg-drafts/issues/11167).

**\[css\-backgrounds\-4\] default background\-origin for \`border\-area\` in shorthand**

* RESOLVED: Using 'border\-area' in the background shorthand \(and omitting origin\) defaults the origin to border\-box

[Discussion.](https://github.com/w3c/csswg-drafts/issues/11167#issuecomment-2474360495)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't support `border-area` yet; that's https://bugzilla.mozilla.org/show_bug.cgi?id=1880365 .

No new bug needed; we can consider this part of that bug. (I added a note there.)
