### ISSUE TITLE
[css-scroll-snap-2] Should scrollsnapchanging target the currently visible element during flings

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1725]
A resolution was made for [csswg-drafts/#10838](https://github.com/w3c/csswg-drafts/issues/10838).

**\[css\-scroll\-snap\-2\] Should scrollsnapchanging target the currently visible element during flings**

* RESOLVED: scrollsnapchanging uses the targeted location for targeted scrolls, but does not predict the destination of momentum scrolling \(uses the current scroll location instead\)

[Discussion.](https://github.com/w3c/csswg-drafts/issues/10838#issuecomment-2536638877)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by jfkthame** [comment]
scroll-snap-2 is https://bugzilla.mozilla.org/show_bug.cgi?id=1843961.
