### ISSUE TITLE
[css-scroll-snap-2] scroll-start-target: auto doesn't match general meaning of auto

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#1726]
A resolution was made for [csswg-drafts/#11173](https://github.com/w3c/csswg-drafts/issues/11173).

**\[css\-scroll\-snap\-2\] scroll\-start\-target: auto doesn't match general meaning of auto**

* RESOLVED: \`scroll\-initial\-target: none &124; nearest\` 

[Discussion.](https://github.com/w3c/csswg-drafts/issues/11173#issuecomment-2536659205)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by jfkthame** [comment]
We haven't implemented scroll-snap-2 yet (https://bugzilla.mozilla.org/show_bug.cgi?id=1843961), so no new bug needed.
