### ISSUE TITLE
[css-multicol] Defining what happens with column-fill in unconstrained containers for continuous and fragmented contexts

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#176]
A resolution was made for [csswg-drafts/#4689](https://github.com/w3c/csswg-drafts/issues/4689).

**\[css\-multicol\] Defining what happens with column\-fill in unconstrained containers for continuous and fragmented contexts**

* RESOLVED: Confirm that we do indeed want \(at least generally\) Firefox's behavior, and get Morten to confirm exactly what he wants clarified in further issues.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4689#issuecomment-577600255)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
No change needed because the spec wants Firefox's behavior.
