### ISSUE TITLE
[css-grid-2] Masonry layout

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#177]
A resolution was made for [csswg-drafts/#4650](https://github.com/w3c/csswg-drafts/issues/4650).

**\[css\-grid\-2\] Masonry layout**

* RESOLVED: Adopt Masonry layout proposal, editors fantasai and Tab, and Mats if he's convinceable

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4650#issuecomment-577614598)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
No change needed.
