### ISSUE TITLE
[css-overflow-4] scrollbar-gutter is too complex

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#179]
A resolution was made for [csswg-drafts/#4674](https://github.com/w3c/csswg-drafts/issues/4674).

**\[css\-overflow\-4\] scrollbar\-gutter is too complex**

* RESOLVED: Move scrollbar\-gutter to the scrollbars spec, add florian as an editor

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4674#issuecomment-577662037)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
No change needed.
