### ISSUE TITLE
[css‑fonts‑4] Add `emoji` as a keyword to `unicode‑range`

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#181]
A resolution was made for [csswg-drafts/#4573](https://github.com/w3c/csswg-drafts/issues/4573).

**\[css‑fonts‑4\] Add \`emoji\` as a keyword to \`unicode‑range\`**

* RESOLVED: we are going to create keywords for unicode ranges

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4573#issuecomment-577727767)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by jfkthame** [comment]
Not ready to implement yet, until this is more fully specced.
