### ISSUE TITLE
[css-text-decor] Clarifying skip-ink:auto behavior in relation to CJK text

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#187]
A resolution was made for [csswg-drafts/#4276](https://github.com/w3c/csswg-drafts/issues/4276).

**\[css\-text\-decor\] Clarifying skip\-ink:auto behavior in relation to CJK text**

* RESOLVED: fully specify an algorithm that specifies ink skipping that references other specifications that isn't codepoint\-by\-codepoint

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4276#issuecomment-578071070)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
No implementation changes required yet.
