### ISSUE TITLE
[css-ruby-1] ruby overhang control

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#188]
A resolution was made for [csswg-drafts/#4492](https://github.com/w3c/csswg-drafts/issues/4492).

**\[css\-ruby\-1\] ruby overhang control**

* RESOLVED: ruby\-overhang auto &124; none on ruby container

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4492#issuecomment-578074029)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by upsuper** [comment]
Let's create a bug for this. I have some plan about implementing it (for long), but haven't got time to get to. I'll probably try to do this in this new decade :D

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1611410
