### ISSUE TITLE
[css-inline-3] initial-letters; feedback from implementation

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#193]
A resolution was made for [csswg-drafts/#4171](https://github.com/w3c/csswg-drafts/issues/4171).

**\[css\-inline\-3\] initial\-letters; feedback from implementation**

* RESOLVED: Use shape\-margin on initial letter when shape\-outside is none and \`inlitial\-letters\-wrap: all\` 

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4171#issuecomment-578112818)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by jfkthame** [comment]
Implementing initial-letter is https://bugzilla.mozilla.org/show_bug.cgi?id=1223880
