### ISSUE TITLE
[css-text] Atomic inlines being equivalent to ID for line breaking is not web-compatible

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#194]
A resolution was made for [csswg-drafts/#4576](https://github.com/w3c/csswg-drafts/issues/4576).

**\[css\-text\] Atomic inlines being equivalent to ID for line breaking is not web\-compatible**

* RESOLVED: Atomic inlines by default always introduce a break opportunity, regardless of context

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4576#issuecomment-578119202)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by jfkthame** [comment]
No change needed in gecko, AIUI - although additional controls may be spec'd in future.
