### ISSUE TITLE
[css‑fonts‑4] Add `emoji` as a keyword to `unicode‑range`

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#204]
A resolution was made for [csswg-drafts/#4573](https://github.com/w3c/csswg-drafts/issues/4573).

**\[css‑fonts‑4\] Add \`emoji\` as a keyword to \`unicode‑range\`**

* RESOLVED: we are going to create keywords for unicode ranges

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4573#issuecomment-578390905)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1929319

**Comment by jfkthame** [comment]
Let's have a bug on file about this, although there isn't a clear, ready-to-implement spec yet (especially for the emoji part of it; Unicode script codes as keywords would be more straightforward).
