### ISSUE TITLE
[css-om-view] Window move and resize functions should be allowed to do nothing

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#205]
A resolution was made for [csswg-drafts/#4728](https://github.com/w3c/csswg-drafts/issues/4728).

**\[css\-om\-view\] Window move and resize functions should be allowed to do nothing**

* RESOLVED: Have smfr put in a blanket MAY saying in some situations browsers can have these functions do nothing

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4728#issuecomment-582674237)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
This doesn't add any more requirements on us.
