### ISSUE TITLE
[css-om-view] Describe layout and visual viewports

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#206]
A resolution was made for [csswg-drafts/#4724](https://github.com/w3c/csswg-drafts/issues/4724).

**\[css\-om\-view\] Describe layout and visual viewports**

* RESOLVED: Start defining what we call layout and visual viewport

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4724#issuecomment-582677042)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
No change here, but FYI @hiikezoe that there is a plan to start defining this.
