### ISSUE TITLE
clarify to what extent new system color are about system settings versus browser settings

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#210]
A resolution was made for [csswg-drafts/#4533](https://github.com/w3c/csswg-drafts/issues/4533).

**clarify to what extent new system color are about system settings versus browser settings**

* RESOLVED: Add clarifying text that all system values are reflecting the browser settings

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4533#issuecomment-585333573)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dbaron** [comment]
Already covered by [bug 1590894](https://bugzilla.mozilla.org/show_bug.cgi?id=1590894).
