### ISSUE TITLE
[css-text-decor] Consider adding an `all` value to `text-decoration-skip-ink`

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#213]
A resolution was made for [csswg-drafts/#4277](https://github.com/w3c/csswg-drafts/issues/4277).

**\[css\-text\-decor\] Consider adding an \`all\` value to \`text\-decoration\-skip\-ink\`**

* RESOLVED: Change the new property to be 'all' not 'always'

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4277#issuecomment-588354602)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by jfkthame** [comment]
This will be handled in bug 1611965.
