### ISSUE TITLE
[css-inline] A question for the procedure to compute the resolved value of "line-height"

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#214]
A resolution was made for [csswg-drafts/#3749](https://github.com/w3c/csswg-drafts/issues/3749).

**\[css\-inline\] A question for the procedure to compute the resolved value of "line\-height"**

* RESOLVED: Line\-height returns 'normal' in gCS for normal and all other give absolute length

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3749#issuecomment-588356281)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
This is our current behavior.
