### ISSUE TITLE
[css-page-3] Add orientation descriptor

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#218]
A resolution was made for [csswg-drafts/#4491](https://github.com/w3c/csswg-drafts/issues/4491).

**\[css\-page\-3\] Add orientation descriptor**

* RESOLVED: Name this page\-orientation with values rotate\-left and rotate\-right

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4491#issuecomment-594967467)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by jfkthame** [comment]
Looks like we shipped page-orientation in https://bugzilla.mozilla.org/show_bug.cgi?id=1869880
