### ISSUE TITLE
[css-pseudo-4] Animations on ::marker?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#223]
A resolution was made for [csswg-drafts/#4814](https://github.com/w3c/csswg-drafts/issues/4814).

**\[css\-pseudo\-4\] Animations on ::marker?**

* RESOLVED: allow transitions on ::marker and allow animations with animations happening and animation rules applying the style

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4814#issuecomment-597749080)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by birtles** [comment]
I'm pretty sure when `layout.css.marker.restricted` is true, we currently disallow CSS animations on `::marker`.

https://searchfox.org/mozilla-central/rev/7d0c94a0e9a9fe1f83553f49b10128567d21709d/servo/components/style/properties/data.py#767-777

(I'm also curious why `opacity` is not allowed in the spec.)

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1637532
