### ISSUE TITLE
[css-inline] initial-letter should allow zero sink?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#225]
A resolution was made for [csswg-drafts/#3698](https://github.com/w3c/csswg-drafts/issues/3698).

**\[css\-inline\] initial\-letter should allow zero sink?**

* RESOLVED: allow sink of 0 for initial letters

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3698#issuecomment-600737962)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by jfkthame** [comment]
`initial-letter` is not yet implemented (https://bugzilla.mozilla.org/show_bug.cgi?id=1223880)
