### ISSUE TITLE
[css-values] Quirky lengths and math expressions

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#232]
Resolutions were made for [csswg-drafts/#4874](https://github.com/w3c/csswg-drafts/issues/4874).

**\[css\-values\] Quirky lengths and math expressions**

* RESOLVED: Properties that accept quirky lengths accept number token which is converted at parse to pixels
* RESOLVED: This resolution does not apply to any quirks inside of calc
* RESOLVED: encourage SVG to follow this approach

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4874#issuecomment-614138114)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
This is what we do.
