### ISSUE TITLE
[css-ruby] Size and position of empty ruby level containers

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#234]
A resolution was made for [csswg-drafts/#4631](https://github.com/w3c/csswg-drafts/issues/4631).

**\[css\-ruby\] Size and position of empty ruby level containers**

* RESOLVED: Empty ruby containers are sized as if they have empty things in them

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4631#issuecomment-614147789)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by upsuper** [comment]
This has already been implemented in [bug 1603354](https://bugzilla.mozilla.org/show_bug.cgi?id=1603354).
