### ISSUE TITLE
[css-contain] editorial: Paint Containment description is incomprehensible

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#237]
A resolution was made for [csswg-drafts/#4946](https://github.com/w3c/csswg-drafts/issues/4946).

**\[css\-contain\] editorial: Paint Containment description is incomprehensible**

* RESOLVED: Accept the comment at the end of https://github.com/w3c/csswg\-drafts/issues/4946\#issuecomment\-614501289

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4946#issuecomment-617892686)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
( @heycam in case it's not a known issue, there seems to be a bug in the mozilla-apprentice bot here --  the URL seems to have been mangled in the generation of this github-issue. `-`  and `#` got slash-escaped, it looks like, which broke the URL)

The correct URL (no slashes) is `https://github.com/w3c/csswg-drafts/issues/4946#issuecomment-614501289` i.e. https://github.com/w3c/csswg-drafts/issues/4946#issuecomment-614501289

**Comment by dholbert** [comment]
In any case, I believe this resolution was effectively just a tweak to use better-defined language, and it's not calling for any behavior-change (and it matches the `contain:paint` behavior that we have implemented).
