### ISSUE TITLE
[css-sizing-3] Mapping HTML’s IMG aspect-ratio behavior into CSS.

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#240]
Resolutions were made for [csswg-drafts/#4951](https://github.com/w3c/csswg-drafts/issues/4951).

**\[css\-sizing\-3\] Mapping HTML’s IMG aspect\-ratio behavior into CSS.**

* RESOLVED: Add an aspect\-ratio option that supports fallback from intrinsic ratio
* RESOLVED: Use the \`&lt;aspect\-ratio&gt;&124;&124;auto\` syntax
* RESOLVED: An aspect ratio specified with the auto option always applies to the content\-box.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4951#issuecomment-621337849)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We implement this now.
