### ISSUE TITLE
[css-ruby] Ruby offset

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#244]
A resolution was made for [csswg-drafts/#4932](https://github.com/w3c/csswg-drafts/issues/4932).

**\[css\-ruby\] Ruby offset**

* RESOLVED: No change, because mbp already handle this case sufficiently.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4932#issuecomment-622119003)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by upsuper** [comment]
We've already supported that. There's nothing we need to do.
