### ISSUE TITLE
[css-ruby] define the height of the content area of ruby bases, ruby annotations

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#245]
A resolution was made for [csswg-drafts/#4935](https://github.com/w3c/csswg-drafts/issues/4935).

**\[css\-ruby\] define the height of the content area of ruby bases, ruby annotations**

* RESOLVED: The height of the content are of ruby boxes and annos is calculated the same as for inline boxes

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4935#issuecomment-622122657)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by upsuper** [comment]
I believe this is what we are already doing.
