### ISSUE TITLE
[css-ruby] define the height of the content area of ruby containers

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#246]
A resolution was made for [csswg-drafts/#4936](https://github.com/w3c/csswg-drafts/issues/4936).

**\[css\-ruby\] define the height of the content area of ruby containers**

* RESOLVED: height of the content area of ruby container box is calculated the same as inline boxes

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4936#issuecomment-622125781)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by upsuper** [comment]
I believe this matches our current behavior.
