### ISSUE TITLE
[css-ruby] Does line-height have an effect on any of the ruby boxes?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#249]
Resolutions were made for [csswg-drafts/#4979](https://github.com/w3c/csswg-drafts/issues/4979).

**\[css\-ruby\] Does line\-height have an effect on any of the ruby boxes?**

* RESOLVED: line\-height on the ruby container doesn't affect the boxes inside
* RESOLVED: ruby containers, ruby bases and ruby base containers act like inline boxes, we'll use line\-height as an example and call out exceptions in the spec
* RESOLVED: line\-height doesn't apply to annotations or annotation containers

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4979#issuecomment-624648356)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by upsuper** [comment]
That's the current Firefox behavior.
