### ISSUE TITLE
[css-text] Styling of soft hyphens

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#25]
A resolution was made for [csswg-drafts/#3863](https://github.com/w3c/csswg-drafts/issues/3863).

**\[css\-text\] Styling of soft hyphens**

* RESOLVED: Add this to the spec

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3863#issuecomment-488500011)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
This is just a clarification of behavior we already have.
