### ISSUE TITLE
[css-ruby] effect of `line-height` on nested ruby containers

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#250]
A resolution was made for [csswg-drafts/#4986](https://github.com/w3c/csswg-drafts/issues/4986).

**\[css\-ruby\] effect of \`line\-height\` on nested ruby containers**

* RESOLVED: nested ruby containers behave as inline boxes for the purpose of line\-height

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4986#issuecomment-624650129)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by upsuper** [comment]
I believe this is the current Firefox behavior.
