### ISSUE TITLE
[css-ruby] Applicability of width & height to various kinds of ruby boxes

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#251]
A resolution was made for [csswg-drafts/#4974](https://github.com/w3c/csswg-drafts/issues/4974).

**\[css\-ruby\] Applicability of width &amp; height to various kinds of ruby boxes**

* RESOLVED: width and height don't apply to  non\-atomic ruby boxes

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4974#issuecomment-624655513)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by upsuper** [comment]
That matches what we do.
