### ISSUE TITLE
[css-ruby] Applicability and effect of margin / border / padding on ruby containers

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#252]
A resolution was made for [csswg-drafts/#4976](https://github.com/w3c/csswg-drafts/issues/4976).

**\[css\-ruby\] Applicability and effect of margin / border / padding on ruby containers**

* RESOLVED: ruby containers behave like inline boxes, and thus behavior of these properties is the same as for regular inline boxes

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4976#issuecomment-624658308)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by upsuper** [comment]
I believe this matches what we do at the moment.
