### ISSUE TITLE
[css-text-decor] Clarifying skip-ink:auto behavior in relation to CJK text

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#254]
A resolution was made for [csswg-drafts/#4276](https://github.com/w3c/csswg-drafts/issues/4276).

**\[css\-text\-decor\] Clarifying skip\-ink:auto behavior in relation to CJK text**

* RESOLVED: Accept PR \#4737, close issue \#4276

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4276#issuecomment-624713965)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by jfkthame** [comment]
This is how Firefox currently behaves.
