### ISSUE TITLE
[css-text] impact of unstyled inlines on hyphenation

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#26]
A resolution was made for [csswg-drafts/#3862](https://github.com/w3c/csswg-drafts/issues/3862).

**\[css\-text\] impact of unstyled inlines on hyphenation**

* RESOLVED: Inline boundaries do not effect hyphenation, styled or unstyled

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3862#issuecomment-488503216)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
Unstyled spans already don't affect hyphenation in Gecko.
