### ISSUE TITLE
[css-ruby-1] Rename ruby-merge: collapse to ruby-merge: merge

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#260]
Resolutions were made for [csswg-drafts/#5004](https://github.com/w3c/csswg-drafts/issues/5004).

**\[css\-ruby\-1\] Rename ruby\-merge: collapse to ruby\-merge: merge**

* RESOLVED: rename ruby\-merge to merge
* RESOLVED: rename collapse value to merge

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5004#issuecomment-628120030)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dbaron** [comment]
still [not implemented](https://bugzilla.mozilla.org/show_bug.cgi?id=ruby-merge)
