### ISSUE TITLE
[css-color-adjust-1] Is forced background-color computed or used value?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#261]
A resolution was made for [csswg-drafts/#4915](https://github.com/w3c/csswg-drafts/issues/4915).

**\[css\-color\-adjust\-1\] Is forced background\-color computed or used value?**

* RESOLVED: The color computed values are defined as used values using the color mix function

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4915#issuecomment-631574709)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We still don't implement those adjustments.
