### ISSUE TITLE
[css-selectors] Can you standardise a pseudo-element selector for file inputs?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#262]
Resolutions were made for [csswg-drafts/#5049](https://github.com/w3c/csswg-drafts/issues/5049).

**\[css\-selectors\] Can you standardise a pseudo\-element selector for file inputs?**

* RESOLVED: expose this selector and name it ::file\-chooser
* RESOLVED: expose this selector and name it ::file\-chooser button

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5049#issuecomment-631580279)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1635675
