### ISSUE TITLE
[css-sizing] Make flex % row-gap resolve to 0 when height is indefinite (only flex, not grid)

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#263]
A resolution was made for [csswg-drafts/#5081](https://github.com/w3c/csswg-drafts/issues/5081).

**\[css\-sizing\] Make flex % row\-gap resolve to 0 when height is indefinite \(only flex, not grid\)**

* RESOLVED: % based gaps for flex in the cause of undefined constraint resolve to 0

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5081#issuecomment-631595507)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1639627

**Comment by dholbert** [comment]
clarifying the resolution (per Tab's correction in a comment on the w3c issue):
> s/cause of undefined constraint/case of resolving against an indefinite constraint/

Anyway, we do need a bug (and a small code change) to address this resolution. [good, apprentice filed one]
