### ISSUE TITLE
[css-position] physical inset properties

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#267]
A resolution was made for [csswg-drafts/#5005](https://github.com/w3c/csswg-drafts/issues/5005).

**\[css\-position\] physical inset properties**

* RESOLVED: Close issue, add a note tot he spec trying to explain the confusion

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5005#issuecomment-634790756)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
No change.
