### ISSUE TITLE
[css-color-adjust-1] Limits on the `only` color scheme keyword

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#269]
A resolution was made for [csswg-drafts/#3881](https://github.com/w3c/csswg-drafts/issues/3881).

**\[css\-color\-adjust\-1\] Limits on the \`only\` color scheme keyword**

* RESOLVED: Remove only keyword, simplify the table, add a note about dropping only

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3881#issuecomment-634799613)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
Not a fan, but no action needed yet.
