### ISSUE TITLE
[css-text] The 'anywhere' value of line-break

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#270]
A resolution was made for [csswg-drafts/#5072](https://github.com/w3c/csswg-drafts/issues/5072).

**\[css\-text\] The 'anywhere' value of line\-break**

* RESOLVED: remove at\-risk label on 'anywhere' value of line\-break

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5072#issuecomment-634800583)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by jfkthame** [comment]
Nothing to do here; we already support this value.
