### ISSUE TITLE
[css-color-adjust-1] Why special-casing background-image for inputs?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#273]
A resolution was made for [csswg-drafts/#4917](https://github.com/w3c/csswg-drafts/issues/4917).

**\[css\-color\-adjust\-1\] Why special\-casing background\-image for inputs?**

* RESOLVED: Remove the special case of background images on input elements wrt forced colors

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4917#issuecomment-638513353)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We don't have such a special case.
