### ISSUE TITLE
[css-inline] should `initial-letter` be plural?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#275]
A resolution was made for [csswg-drafts/#862](https://github.com/w3c/csswg-drafts/issues/862).

**\[css\-inline\] should \`initial\-letter\` be plural?**

* RESOLVED: Rename initial\-letters to initial\-letter

[Discussion.](https://github.com/w3c/csswg-drafts/issues/862#issuecomment-638517238)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
We have `initial-letter` (singular) defined [here](https://searchfox.org/mozilla-central/rev/7cadba1d8b8feaec4615f5bb98aac4b8a719793c/servo/components/style/properties/longhands/text.mako.rs#61). No action needed.
