### ISSUE TITLE
[css-inline] better name for initial-letters property

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#276]
A resolution was made for [csswg-drafts/#2950](https://github.com/w3c/csswg-drafts/issues/2950).

**\[css\-inline\] better name for initial\-letters property**

* RESOLVED: Stay with the name initial\-letter

[Discussion.](https://github.com/w3c/csswg-drafts/issues/2950#issuecomment-638517723)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
No action needed for a spec discussion.
