### ISSUE TITLE
[css-inline-3] Sizing atomic inlines as initial letters

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#277]
A resolution was made for [csswg-drafts/#3231](https://github.com/w3c/csswg-drafts/issues/3231).

**\[css\-inline\-3\] Sizing atomic inlines as initial letters**

* RESOLVED: Atomic inline initial letter size as regular atomic inlines, except for auto sizes being calculated using the initial letter algorithm

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3231#issuecomment-638518056)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We don't implement initial-letters yet
