### ISSUE TITLE
[css-inline-3] shape-margin on initial-letters-wrap: first

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#278]
A resolution was made for [csswg-drafts/#5117](https://github.com/w3c/csswg-drafts/issues/5117).

**\[css\-inline\-3\] shape\-margin on initial\-letters\-wrap: first**

* RESOLVED: shape\-margin and shape\-outside apply to initial letter wrapped inline boxes, modifying or replacing the shape of the glyph

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5117#issuecomment-638519104)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We don't implement initial-letters yet.
