### ISSUE TITLE
[mediaqueries] Define Media Groups: continuous vs paged, etc.

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#279]
A resolution was made for [csswg-drafts/#5019](https://github.com/w3c/csswg-drafts/issues/5019).

**\[mediaqueries\] Define Media Groups: continuous vs paged, etc.**

* RESOLVED: Add definitions for paged and continuous media to MQ4

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5019#issuecomment-638521048)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
No action needed for now afaict.
