### ISSUE TITLE
[css-color-adjust-1] Should probably not honor non-url background images

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#283]
A resolution was made for [csswg-drafts/#4916](https://github.com/w3c/csswg-drafts/issues/4916).

**\[css\-color\-adjust\-1\] Should probably not honor non\-url background images**

* RESOLVED: Do not honor non\-URL background images in forced color adjustments

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4916#issuecomment-642134981)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
That's what we do.
