### ISSUE TITLE
[css-color-adjust-1][mediaqueries-5] Fold `forced-colors` and `prefers-contrast`?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#284]
A resolution was made for [csswg-drafts/#3856](https://github.com/w3c/csswg-drafts/issues/3856).

**\[css\-color\-adjust\-1\]\[mediaqueries\-5\] Fold \`forced\-colors\` and \`prefers\-contrast\`?**

* RESOLVED: add the forced value to prefers\-contrast

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3856#issuecomment-642139541)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
No bug needed.
