### ISSUE TITLE
[css-values] attr()'s url type seems wrong

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#290]
A resolution was made for [csswg-drafts/#5079](https://github.com/w3c/csswg-drafts/issues/5079).

**\[css\-values\] attr\(\)'s url type seems wrong**

* RESOLVED: Specify we use host document behavior for URL types in attr\(\)

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5079#issuecomment-648926142)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We'll get to that.
