### ISSUE TITLE
[css-mediaqueries] Precisely define which media features an undisplayed page has.

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#291]
A resolution was made for [csswg-drafts/#3800](https://github.com/w3c/csswg-drafts/issues/3800).

**\[css\-mediaqueries\] Precisely define which media features an undisplayed page has.**

* RESOLVED: Do testing in this area and specify values for this case

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3800#issuecomment-648932524)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
No action needed for now.
