### ISSUE TITLE
[css-align] Content-distribution keywords that fall back to "center" can't be made safe

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#293]
A resolution was made for [csswg-drafts/#5088](https://github.com/w3c/csswg-drafts/issues/5088).

**\[css\-align\] Content\-distribution keywords that fall back to "center" can't be made safe**

* RESOLVED: Change the fallback value for space\-around and space\-evenly to safe center

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5088#issuecomment-648940841)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
Track in https://bugzilla.mozilla.org/show_bug.cgi?id=1836206
