### ISSUE TITLE
[css-sizing-4] Should aspect-ratio be used for abspos `top: 0; bottom: 0;`?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#296]
A resolution was made for [csswg-drafts/#5151](https://github.com/w3c/csswg-drafts/issues/5151).

**\[css\-sizing\-4\] Should aspect\-ratio be used for abspos \`top: 0; bottom: 0;\`?**

* RESOLVED: Accept proposal

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5151#issuecomment-652702595)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
Ya, need a bug for this

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1651776
