### ISSUE TITLE
[css-sizing-4] Should aspect-ratio affect the intrinsic size?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#297]
A resolution was made for [csswg-drafts/#5032](https://github.com/w3c/csswg-drafts/issues/5032).

**\[css\-sizing\-4\] Should aspect\-ratio affect the intrinsic size?**

* RESOLVED: Min\-content and max\-content keywords represent size of element at top and bottom extremes of fit\-content or shrink\-to\-fit sizing and therefore match size it would take under a min or max constraint when taking aspect\-ratio into account

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5032#issuecomment-655637111)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
@BorisChiou does the resolution match your patch's current behavior?

**Comment by BorisChiou** [comment]
No. So I filed a bug for this: https://bugzilla.mozilla.org/show_bug.cgi?id=1646100

**Comment by aethanyc** [comment]
Close this because a bug is filed.
