### ISSUE TITLE
[css-grid] Does grid-template-areas really expand the explicit grid?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#300]
A resolution was made for [csswg-drafts/#4914](https://github.com/w3c/csswg-drafts/issues/4914).

**\[css\-grid\] Does grid\-template\-areas really expand the explicit grid?**

* RESOLVED: Accept edits to spec for explicit grid

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4914#issuecomment-658872532)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
AFAICT from https://github.com/w3c/csswg-drafts/issues/4914#issuecomment-608781865 and subsequent comments, this resolution was just about clarifying the spec to match implementations' behavior.

So, no change needed on our end.
