### ISSUE TITLE
[css-grid] Intrinsic contributions for items spanning flex tracks are not web compatible

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#303]
Resolutions were made for [csswg-drafts/#4783](https://github.com/w3c/csswg-drafts/issues/4783).

**\[css\-grid\] Intrinsic contributions for items spanning flex tracks are not web compatible**

* RESOLVED: The auto minimum size is zero for grid items that span multiple tracks when at least one of those tracks is flexible.
* RESOLVED: When destributing the intrinsic contribution of a grid item, if it spans flexible tracks, excess size is distributed to those tracks and not to fixed/auto sized tracks.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4783#issuecomment-664627235)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
I think we can handle this in https://bugzilla.mozilla.org/show_bug.cgi?id=1530097.
