### ISSUE TITLE
[css-sizing] `height: stretch` should just behave as `height: auto`

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#305]
A resolution was made for [csswg-drafts/#1614](https://github.com/w3c/csswg-drafts/issues/1614).

**\[css\-sizing\] \`height: stretch\` should just behave as \`height: auto\`**

* RESOLVED: height\-stretch behaves as better 100% where align\-stretch self isn't possible

[Discussion.](https://github.com/w3c/csswg-drafts/issues/1614#issuecomment-664655070)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
We don't implement `stretch` yet.
