### ISSUE TITLE
[css-inline-3] initial-letters-wrap: first, whitespace collapse needs defining

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#308]
A resolution was made for [csswg-drafts/#5120](https://github.com/w3c/csswg-drafts/issues/5120).

**\[css\-inline\-3\] initial\-letters\-wrap: first, whitespace collapse needs defining**

* RESOLVED: preserve whitespace for sink 1, collapse otherwise

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5120#issuecomment-665255110)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
We don't implement (most of) initial-letters.
