### ISSUE TITLE
[css-inline-3] Drop 'hebrew' alignment from initial-letter-align

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#309]
A resolution was made for [csswg-drafts/#5208](https://github.com/w3c/csswg-drafts/issues/5208).

**\[css\-inline\-3\] Drop 'hebrew' alignment from initial\-letter\-align**

* RESOLVED: remove hebrew value from initial\-letter\-align

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5208#issuecomment-665256640)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
We don't implement enough of initial-letters yet.
