### ISSUE TITLE
[css-inline] alignment of initial-letter for South Asian scripts without hanging baseline

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#310]
A resolution was made for [csswg-drafts/#864](https://github.com/w3c/csswg-drafts/issues/864).

**\[css\-inline\] alignment of initial\-letter for South Asian scripts without hanging baseline**

* RESOLVED: add \`leading\` value to \`initial\-letter\-align\`, and get feedback to confirm it solves the issues for these scripts

[Discussion.](https://github.com/w3c/csswg-drafts/issues/864#issuecomment-665265708)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
We don't implement enough of initial-letters yet.
