### ISSUE TITLE
[css-inline-3] text-align + initial-letter

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#311]
A resolution was made for [csswg-drafts/#5207](https://github.com/w3c/csswg-drafts/issues/5207).

**\[css\-inline\-3\] text\-align \+ initial\-letter**

* RESOLVED: make drop caps behave like raise caps for the purposes of text\-align and justification

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5207#issuecomment-665283468)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
We don't implement enough of initial-letters yet.
