### ISSUE TITLE
[css-inline-3] initial-letters: interaction of shape-margin and regular margin

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#312]
A resolution was made for [csswg-drafts/#5119](https://github.com/w3c/csswg-drafts/issues/5119).

**\[css\-inline\-3\] initial\-letters: interaction of shape\-margin and regular margin**

* RESOLVED: Make shape\-outside and margin interact the same way for initial letters as for floats

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5119#issuecomment-665287944)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
We don't implement enough of initial-letters yet.
