### ISSUE TITLE
[css-inline-3] leading-trim through to descendant line boxes

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#313]
A resolution was made for [csswg-drafts/#5237](https://github.com/w3c/csswg-drafts/issues/5237).

**\[css\-inline\-3\] leading\-trim through to descendant line boxes**

* RESOLVED: Don't drill through in a way we can  block boxes with non\-zero padding / border in the block axis

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5237#issuecomment-665292525)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
We don't implement leading-trim.
