### ISSUE TITLE
[css-text] letter-spacing should not apply to the end edge of a line/span?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#319]
A resolution was made for [csswg-drafts/#1518](https://github.com/w3c/csswg-drafts/issues/1518).

**\[css\-text\] letter\-spacing should not apply to the end edge of a line/span?**

* RESOLVED: Change Text L3 to a may for the behavior and transfer switch discussion to Text L4

[Discussion.](https://github.com/w3c/csswg-drafts/issues/1518#issuecomment-665354152)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by jfkthame** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1907305
