### ISSUE TITLE
[css-color-adjust] Animation type of forced-color-adjust

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#337]
A resolution was made for [csswg-drafts/#5342](https://github.com/w3c/csswg-drafts/issues/5342).

**\[css\-color\-adjust\] Animation type of forced\-color\-adjust**

* RESOLVED: make forced\-color\-adjust not animatable

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5342#issuecomment-669593075)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by birtles** [comment]
We don't implement this yet ([bug 1591210](https://bugzilla.mozilla.org/show_bug.cgi?id=1591210)) but presumably when we do, we'll make it not animatable.
