### ISSUE TITLE
[mediaqueries-5] `prefers-contrast: high` media feature doesn't account for macOS and iOS

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#339]
A resolution was made for [csswg-drafts/#2943](https://github.com/w3c/csswg-drafts/issues/2943).

**\[mediaqueries\-5\] \`prefers\-contrast: high\` media feature doesn't account for macOS and iOS**

* RESOLVED: Change high and low in the MQ to more and less

[Discussion.](https://github.com/w3c/csswg-drafts/issues/2943#issuecomment-672994920)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
@zekemedley is already on top of this in https://bugzilla.mozilla.org/show_bug.cgi?id=1658780
