### ISSUE TITLE
Allow specifying the "accent color" of a form control element

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#342]
A resolution was made for [csswg-drafts/#5187](https://github.com/w3c/csswg-drafts/issues/5187).

**Allow specifying the "accent color" of a form control element**

* RESOLVED: The group wants to add accent\-color and discussion on details will continue

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5187#issuecomment-680996476)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by jfkthame** [comment]
This isn't to the point of being ready to implement yet.
