### ISSUE TITLE
[css-logical] Mapping of logical values in 'resize' 

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#359]
A resolution was made for [csswg-drafts/#3281](https://github.com/w3c/csswg-drafts/issues/3281).

**\[css\-logical\] Mapping of logical values in 'resize' **

* RESOLVED: have the logical value of resize that of the element itself

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3281#issuecomment-693512638)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
Based on the discussion, it sounded like the resolved-on behavior matches what Gecko already does. (@emilio can hopefully sanity-check my understanding on that)

**Comment by emilio** [comment]
That's right, but we need a bug for https://github.com/w3c/csswg-drafts/issues/2821#issuecomment-415092595 instead.
