### ISSUE TITLE
[css-text] Reconsider the resolution on #855

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#360]
A resolution was made for [csswg-drafts/#5410](https://github.com/w3c/csswg-drafts/issues/5410).

**\[css\-text\] Reconsider the resolution on \#855**

* RESOLVED: Treat CR as an ordinary space

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5410#issuecomment-693517255)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
@emilio I think we need a bug for this, correct?

**Comment by emilio** [comment]
Yes

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1665423
