### ISSUE TITLE
[cssom] Add IDL "MathMLElement includes ElementCSSInlineStyle;"

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#363]
A resolution was made for [csswg-drafts/#5513](https://github.com/w3c/csswg-drafts/issues/5513).

**\[cssom\] Add IDL "MathMLElement includes ElementCSSInlineStyle;"**

* RESOLVED: accept a PR to add CSSOM for MathML

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5513#issuecomment-694372315)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by fred-wang** [comment]
cc @emilio 

This is already implemented in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1571487 so can be closed
