### ISSUE TITLE
[css-scroll-snap] [css-scroll-anchoring] Clarify the interaction between snapping and scroll anchoring

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#366]
A resolution was made for [csswg-drafts/#4830](https://github.com/w3c/csswg-drafts/issues/4830).

**\[css\-scroll\-snap\] \[css\-scroll\-anchoring\] Clarify the interaction between snapping and scroll anchoring**

* RESOLVED: scroll\-snap overrides scroll\-anchoring for behavior heuristics

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4830#issuecomment-701498238)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
Tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1530253
