### ISSUE TITLE
[css-grid-1] Fix aspect-ratio errors in css-grid-1

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#380]
A resolution was made for [csswg-drafts/#5615](https://github.com/w3c/csswg-drafts/issues/5615).

**\[css\-grid\-1\] Fix aspect\-ratio errors in css\-grid\-1**

* RESOLVED: accept aspect\-ratio error changes in css\-grid\-1

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5615#issuecomment-712425913)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
Will do this in https://bugzilla.mozilla.org/show_bug.cgi?id=1646098
