### ISSUE TITLE
[css-2020] Clear 'aspect-ratio' for shipping

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#382]
A resolution was made for [csswg-drafts/#5598](https://github.com/w3c/csswg-drafts/issues/5598).

**\[css\-2020\] Clear 'aspect\-ratio' for shipping**

* RESOLVED: add aspect\-ratio to the "clear for shipping despite not being in CR" section of snapshot\-2020

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5598#issuecomment-712433857)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
At editorial change. No action needed for implementations.
