### ISSUE TITLE
[css-values-4] Ratio of `0/0`?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#385]
A resolution was made for [csswg-drafts/#4954](https://github.com/w3c/csswg-drafts/issues/4954).

**\[css\-values\-4\] Ratio of \`0/0\`?**

* RESOLVED: Define aspect\-ratio: 0/0 to be equal to aspect\-ratio: calc\(0/0\)

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4954#issuecomment-712470122)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
@BorisChiou do we need a bug?

**Comment by BorisChiou** [comment]
Yes. We should revisit 0/0 in all layout modes in that bug.

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1672512
