### ISSUE TITLE
[cssom] [mediaqueries] Media query serialization doesn't work for newer spec features

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#386]
A resolution was made for [csswg-drafts/#5627](https://github.com/w3c/csswg-drafts/issues/5627).

**\[cssom\] \[mediaqueries\] Media query serialization doesn't work for newer spec features**

* RESOLVED: Do not sort or dedup MQs when serializing

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5627#issuecomment-712475204)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We do this.
