### ISSUE TITLE
[css-contain] contain:size needs to mention its effect on aspect-ratio

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#389]
A resolution was made for [csswg-drafts/#5585](https://github.com/w3c/csswg-drafts/issues/5585).

**\[css\-contain\] contain:size needs to mention its effect on aspect\-ratio**

* RESOLVED: contain:size suppresses intrinsic aspect ratio

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5585#issuecomment-713158240)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
The resolution matches our behavior as of https://bugzilla.mozilla.org/show_bug.cgi?id=1660122
