### ISSUE TITLE
[css-sizing-4][css-contain] Clarify on specifying aspect-ratio and contain:size on replaced elements

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#393]
A resolution was made for [csswg-drafts/#5550](https://github.com/w3c/csswg-drafts/issues/5550).

**\[css\-sizing\-4\]\[css\-contain\] Clarify on specifying aspect\-ratio and contain:size on replaced elements**

* RESOLVED: Add an exampe, but no change to normative prose

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5550#issuecomment-713166309)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
This resolution matches our behavior as of https://bugzilla.mozilla.org/show_bug.cgi?id=1660122
