### ISSUE TITLE
[css-sizing-3] Why was min-content, etc. redefined to do nothing in the block axis?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#394]
A resolution was made for [csswg-drafts/#3973](https://github.com/w3c/csswg-drafts/issues/3973).

**\[css\-sizing\-3\] Why was min\-content, etc. redefined to do nothing in the block axis?**

* RESOLVED: accept edits made

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3973#issuecomment-713177741)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
@BorisChiou is this something you need to take into account in your aspect-ratio work?

**Comment by BorisChiou** [comment]
This may be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1646100. However, I believe we should fix this in general cases (without `aspect-ratio`) first. Perhaps we need to file a bug for this.

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1672559
