### ISSUE TITLE
[css-overflow] CSSOM scrollWidth/scrollHeight behaviour of "overflow: clip".

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#417]
A resolution was made for [csswg-drafts/#5572](https://github.com/w3c/csswg-drafts/issues/5572).

**\[css\-overflow\] CSSOM scrollWidth/scrollHeight behaviour of "overflow: clip".**

* RESOLVED: scrollWidth/scrollHeight ignore overflow:clip when computing the value

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5572#issuecomment-715448943)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
Per @MatsPalmgren's comment in https://bugzilla.mozilla.org/show_bug.cgi?id=1668714#c5, this resolution matches Firefox's current behavior.
