### ISSUE TITLE
[css-sizing-4] How to handle 0 in aspect-ratio

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#422]
A resolution was made for [csswg-drafts/#5557](https://github.com/w3c/csswg-drafts/issues/5557).

**\[css\-sizing\-4\] How to handle 0 in aspect\-ratio**

* RESOLVED: Treat aspect ratio of 0 or infinity as auto on Thursday 22 October 2020

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5557#issuecomment-720915929)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
Fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1672793.
