### ISSUE TITLE
[css-flexbox] Should definite cross size be used to compute flex item's transferred size suggestion?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#423]
A resolution was made for [csswg-drafts/#5663](https://github.com/w3c/csswg-drafts/issues/5663).

**\[css\-flexbox\] Should definite cross size be used to compute flex item's transferred size suggestion?**

* RESOLVED: close this issue as an editorial change

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5663#issuecomment-722042259)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
The issue resolves to Firefox's currently behavior.
