### ISSUE TITLE
Move -webkit- prefixed aliases into flexbox?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#424]
Resolutions were made for [csswg-drafts/#5634](https://github.com/w3c/csswg-drafts/issues/5634).

**Move \-webkit\- prefixed aliases into flexbox?**

* RESOLVED: Add an appendix to flexbox spec for the webkit prefix properties
* RESOLVED: Add these to the appendix as MUST or MAY depending on impl and SHOULD NOT for authors. Add details about how they're not simple aliases

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5634#issuecomment-722049318)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
Just a spec organization change.
