### ISSUE TITLE
[css-sizing] how should inline-axis intrinsic sizing work for 'fit-content' and 'fit-content()'?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#426]
A resolution was made for [csswg-drafts/#3731](https://github.com/w3c/csswg-drafts/issues/3731).

**\[css\-sizing\] how should inline\-axis intrinsic sizing work for 'fit\-content' and 'fit\-content\(\)'?**

* RESOLVED: Close this issue as fixed

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3731#issuecomment-722053572)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
Should be addressed in  Bug 1312588.
