### ISSUE TITLE
[css-values-4] How to interpolate <ratio>?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#427]
A resolution was made for [csswg-drafts/#4953](https://github.com/w3c/csswg-drafts/issues/4953).

**\[css\-values\-4\] How to interpolate &lt;ratio&gt;?**

* RESOLVED: Interpolate ratios using log

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4953#issuecomment-722054926)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1670155
