### ISSUE TITLE
Wide Review of CSS Fonts 4

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#429]
A resolution was made for [csswg-drafts/#4944](https://github.com/w3c/csswg-drafts/issues/4944).

**Wide Review of CSS Fonts 4**

* RESOLVED: republish a new WD

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4944#issuecomment-725550167)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
No change needed for Firefox.
