### ISSUE TITLE
[cssom-view] [css-overflow] Document.scrollingElement doesn't reflect viewport propagation correctly in presence of overflow: clip

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#430]
A resolution was made for [csswg-drafts/#5601](https://github.com/w3c/csswg-drafts/issues/5601).

**\[cssom\-view\] \[css\-overflow\] Document.scrollingElement doesn't reflect viewport propagation correctly in presence of overflow: clip**

* RESOLVED: For quirks mode only the scrolling element should follow same propagation as the overflow:clip

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5601#issuecomment-725562407)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1665796
