### ISSUE TITLE
[cssom-view] No way to access the viewport size without losing precision.

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#431]
A resolution was made for [csswg-drafts/#5260](https://github.com/w3c/csswg-drafts/issues/5260).

**\[cssom\-view\] No way to access the viewport size without losing precision.**

* RESOLVED: No change

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5260#issuecomment-725566976)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
Nightly compat experiment in https://bugzilla.mozilla.org/show_bug.cgi?id=1676843.
