### ISSUE TITLE
[css-sizing-4] Allow specifying only one dimension for intrinsic sizing

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#439]
A resolution was made for [csswg-drafts/#5432](https://github.com/w3c/csswg-drafts/issues/5432).

**\[css\-sizing\-4\] Allow specifying only one dimension for intrinsic sizing**

* RESOLVED: Property takes 4 longhands, logical and physical, which have a normal value

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5432#issuecomment-737585853)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
I added a note on https://bugzilla.mozilla.org/show_bug.cgi?id=1597529 (which is filed on implementing this feature) to note this change.
