### ISSUE TITLE
[css-contain-2] apply containment on `content-visibility: visible` ; use `normal` as initial value

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#440]
A resolution was made for [csswg-drafts/#5695](https://github.com/w3c/csswg-drafts/issues/5695).

**\[css\-contain\-2\] apply containment on \`content\-visibility: visible\` ; use \`normal\` as initial value**

* RESOLVED: Have separate keywords for the visbile and contained value vs initial value

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5695#issuecomment-737587611)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't implement this property yet, so no new bug is needed. Its implementation is tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1660384
