### ISSUE TITLE
[css-overflow-3] Add box-edge values to overflow-clip-margin

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#455]
A resolution was made for [csswg-drafts/#5801](https://github.com/w3c/csswg-drafts/issues/5801).

**\[css\-overflow\-3\] Add box\-edge values to overflow\-clip\-margin**

* RESOLVED: Add the box keywords to the overflow\-clip\-margin

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5801#issuecomment-755815008)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
I'll add a note on https://bugzilla.mozilla.org/show_bug.cgi?id=1661582 (the bug on implementing this property) to mention this change.
