### ISSUE TITLE
[Cascade / Pseudo-elements / Values / Fragmentation] currentColor when fragments have differents colors

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#456]
Resolutions were made for [csswg-drafts/#1510](https://github.com/w3c/csswg-drafts/issues/1510).

**\[Cascade / Pseudo\-elements / Values / Fragmentation\] currentColor when fragments have differents colors**

* RESOLVED: Color inherits according to first line inheritance. currentColor keys off value of that fragment per fragment
* RESOLVED: Have font\-relative units key off the font size per fragment

[Discussion.](https://github.com/w3c/csswg-drafts/issues/1510#issuecomment-755816654)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
If I followed the discussion correctly, the resolution was basically to match what Firefox already does. So there's no change needed on our end.
