### ISSUE TITLE
[css-sizing-4][css-contain-2] Revisiting auto-sizing when size-containment applies

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#460]
A resolution was made for [csswg-drafts/#5668](https://github.com/w3c/csswg-drafts/issues/5668).

**\[css\-sizing\-4\]\[css\-contain\-2\] Revisiting auto\-sizing when size\-containment applies**

* RESOLVED: align the behavior of auto sizing for size\-containment with that of resizeObserver

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5668#issuecomment-759602039)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
This is about `content-visibility` which we don't implement yet.
