### ISSUE TITLE
[css-ui-4] Use of accent color outside of form control elements

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#472]
A resolution was made for [csswg-drafts/#5657](https://github.com/w3c/csswg-drafts/issues/5657).

**\[css\-ui\-4\] Use of accent color outside of form control elements**

* RESOLVED: UAs may use an accent\-color outside of form controls at their discretion

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5657#issuecomment-768451736)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't implement this yet, so no bug required for the change.
