### ISSUE TITLE
[css-values-4] min/max(%, %) should explicitly evaluate against the % value, not the resolved value

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#473]
A resolution was made for [csswg-drafts/#4227](https://github.com/w3c/csswg-drafts/issues/4227).

**\[css\-values\-4\] min/max\(%, %\) should explicitly evaluate against the % value, not the resolved value**

* RESOLVED: Close no change

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4227#issuecomment-768453578)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1689244 on this rather than letting the apprentice do it (because the name of the csswg issue is actually the opposite of what ended up being resolved, so it wouldn't make for a good bug description).
