### ISSUE TITLE
[css-cascade] Do we need a keyword similar to `revert`, but for cascade layers?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#479]
A resolution was made for [csswg-drafts/#5793](https://github.com/w3c/csswg-drafts/issues/5793).

**\[css\-cascade\] Do we need a keyword similar to \`revert\`, but for cascade layers?**

* RESOLVED: Add revert\-layer to Cascade 5

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5793#issuecomment-777858060)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
This is a feature that we don't implement yet.
