### ISSUE TITLE
[css-cascade] Cascade layers need an import syntax

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#480]
A resolution was made for [csswg-drafts/#5681](https://github.com/w3c/csswg-drafts/issues/5681).

**\[css\-cascade\] Cascade layers need an import syntax**

* RESOLVED: Cascade layer imports is done using @import followed by URL followed by layer declaration

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5681#issuecomment-777868916)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
This is a feature that we don't implement yet.
