### ISSUE TITLE
[css-cascade] Should unnamed cascade layers be allowed?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#481]
A resolution was made for [csswg-drafts/#5792](https://github.com/w3c/csswg-drafts/issues/5792).

**\[css\-cascade\] Should unnamed cascade layers be allowed?**

* RESOLVED: We will allow unnamed cascade layers

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5792#issuecomment-777871988)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
we don't implement this feature yet.
