### ISSUE TITLE
[css-page] Should page descriptors support `!important`?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#483]
A resolution was made for [csswg-drafts/#5970](https://github.com/w3c/csswg-drafts/issues/5970).

**\[css\-page\] Should page descriptors support \`!important\`?**

* RESOLVED: The stuff inside @page or @margin rule are descriptors but act like properties for behavior and cascade

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5970#issuecomment-780728177)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
@emilio did this resolution end up matching our existing behavior, or do we need a bug on this?

**Comment by emilio** [comment]
Matches current behavior.
