### ISSUE TITLE
[css-images-3] image-rendering:pixelated should not force "nearest neighbor" (or similar) when the scale factor is far from an integer (e.g. 150%)

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#485]
A resolution was made for [csswg-drafts/#5837](https://github.com/w3c/csswg-drafts/issues/5837).

**\[css\-images\-3\] image\-rendering:pixelated should not force "nearest neighbor" \(or similar\) when the scale factor is far from an integer \(e.g. 150%\)**

* RESOLVED: Bake the smoothing into non\-int changes in current pixelated value. Add a new value for nearest neighbor jaggedness

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5837#issuecomment-785259691)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't implement `pixelated` right now, so no change needed. (It's blocked on https://bugzilla.mozilla.org/show_bug.cgi?id=1072703 , which this resolution kind of extends; I'll add a note there.)
