### ISSUE TITLE
[css-color-5] More clarity around the percentage in color-mix()

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#488]
A resolution was made for [csswg-drafts/#6064](https://github.com/w3c/csswg-drafts/issues/6064).

**\[css\-color\-5\] More clarity around the percentage in color\-mix\(\)**

* RESOLVED: color\-mix\(&lt;metadata&gt;, &lt;color\-option&gt;\#{2}\), where &lt;color\-option&gt; = &lt;color&gt; &amp;&amp; &lt;percentage&gt;?

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6064#issuecomment-790197866)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We do this.
