### ISSUE TITLE
[css-text] Tabs and the end of the line with pre-wrap and break-word

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#493]
A resolution was made for [csswg-drafts/#6062](https://github.com/w3c/csswg-drafts/issues/6062).

**\[css\-text\] Tabs and the end of the line with pre\-wrap and break\-word**

* RESOLVED: For white\-space:pre\-wrap tabs hang like spaces do

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6062#issuecomment-800045501)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
Dupe of #77 .  (This one got spawned by a github comment that was quoting a resolution.)
