### ISSUE TITLE
[css-fonts-5] Add glyph scaling override descriptor to @font-face

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#495]
A resolution was made for [csswg-drafts/#6075](https://github.com/w3c/csswg-drafts/issues/6075).

**\[css\-fonts\-5\] Add glyph scaling override descriptor to @font\-face**

* RESOLVED: Add a size\-adjust descriptor to @fontface, accepting a %. Applies a scale factor. Impacts all associated metrics of the font, including the outlinet b/c does not effect computed fonts size does not effect em

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6075#issuecomment-801224623)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by jfkthame** [comment]
This is already on file as https://bugzilla.mozilla.org/show_bug.cgi?id=1698495.
