### ISSUE TITLE
[css-color-4] Concerns about color() function fallback

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#496]
A resolution was made for [csswg-drafts/#5931](https://github.com/w3c/csswg-drafts/issues/5931).

**\[css\-color\-4\] Concerns about color\(\) function fallback**

* RESOLVED: remove color\(\) function fallback

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5931#issuecomment-801233734)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't implement this feature yet (https://bugzilla.mozilla.org/show_bug.cgi?id=1128204 is filed on implementing it).
