### ISSUE TITLE
[Cascade / Pseudo-elements / Values / Fragmentation] currentColor when fragments have differents colors

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#503]
A resolution was made for [csswg-drafts/#1510](https://github.com/w3c/csswg-drafts/issues/1510).

**\[Cascade / Pseudo\-elements / Values / Fragmentation\] currentColor when fragments have differents colors**

* RESOLVED: The return value of gCS to match FF behavior that first\-line is ignored in gCS

[Discussion.](https://github.com/w3c/csswg-drafts/issues/1510#issuecomment-811191452)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We do this.
