### ISSUE TITLE
[css-fonts] Computed value of font stretch

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#506]
A resolution was made for [csswg-drafts/#6171](https://github.com/w3c/csswg-drafts/issues/6171).

**\[css\-fonts\] Computed value of font stretch**

* RESOLVED: font\-stretch should serialize to a number/percentage, not a keyword

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6171#issuecomment-814152642)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
We do this.
