### ISSUE TITLE
[css-fonts-5] How do font-size-adjust property and size-adjust descriptor work together?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#509]
A resolution was made for [csswg-drafts/#6128](https://github.com/w3c/csswg-drafts/issues/6128).

**\[css\-fonts\-5\] How do font\-size\-adjust property and size\-adjust descriptor work together?**

* RESOLVED: clarify that font\-size\-adjust computations will effect things in such a way that the descriptor overrides have no effect

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6128#issuecomment-814172364)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
I believe this is how our prototype behaves, mind confirming (and if so closing) @jfkthame?

**Comment by jfkthame** [comment]
That's correct.
