### ISSUE TITLE
[css-pseudo] questions about text decorations on highlight pseudos

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#512]
A resolution was made for [csswg-drafts/#6022](https://github.com/w3c/csswg-drafts/issues/6022).

**\[css\-pseudo\] questions about text decorations on highlight pseudos**

* RESOLVED: Text decos of highlight pseudos sort \*outermost\* by deco category \(per CSS2\) then by highlight type. ::selection has an out to allow it to paint on top of everything else.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6022#issuecomment-816224154)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
In addition to the above-quoted resolution, fantasai added (on the github issue):
> So for clarity, we resolved on the UA having the choice of:
> 
>    d) original underline / ::selection underline / ::target-text overline / ::selection text / original strike-through / ::target-text strike-through (1=yes, 2=yes)
 >   e) original underline / ::target-text overline / original strike-through / ::target-text strike-through / ::selection underline / ::selection text

Anyway: this is a feature we don't implement yet, AFAIK. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1703963 on the general feature.

**Comment by delan** [comment]
Note also the answers to my original questions (for whenever you start implementing):

> Given the following content, with both the ::selection and ::target-text highlights marked {between the braces}:
> 
> ```html
> <span class="foo">before {foo</span>
> <span class="bar">bar} after</span>
> ```
> ```css
> .foo, .bar { text-decoration: yellow solid line-through; }
> ::target-text /* :root or *, doesn’t matter */ { background-color: orange; }
> ::selection /* :root or *, doesn’t matter */ { background-color: green; }
> .foo::selection { color: cyan; text-decoration-color: magenta; /* no text-decoration-line */ }
> .bar::target-text { color: xxx; text-decoration: red dotted line-through; }
> .bar::selection { color: yyy; text-decoration: blue wavy line-through; }
> ```
> 
> 1. What should be painted at “foo” and in what order (topmost last)?
>    * **d) orange, green, cyan “foo”, cyan solid**
> 2. What should be painted at “bar” and in what order (topmost last)?
>    * **d) orange, green, yyy “bar”, yyy solid, red dotted, blue wavy**
