### ISSUE TITLE
[css-highlight-api] maplike vs setlike

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#513]
A resolution was made for [csswg-drafts/#5910](https://github.com/w3c/csswg-drafts/issues/5910).

**\[css\-highlight\-api\] maplike vs setlike**

* RESOLVED: Switch Highlights back to a maplike of \(name\)=&gt; Highlight, add a Note about what happens if you register the same highlight with multiple names

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5910#issuecomment-816245337)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
I don't think we implement this API yet. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1703961 to track implementing the API in general.
