### ISSUE TITLE
Capitalization: "User Agent" or "user agent"

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#516]
A resolution was made for [csswg-drafts/#5200](https://github.com/w3c/csswg-drafts/issues/5200).

**Capitalization: "User Agent" or "user agent"**

* RESOLVED: Match the style guide of lowercase for "user agent"

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5200#issuecomment-816277506)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
Editorial
