### ISSUE TITLE
[css-ruby] replaced annotation containers and base containers are nonsensical

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#530]
A resolution was made for [csswg-drafts/#6000](https://github.com/w3c/csswg-drafts/issues/6000).

**\[css\-ruby\] replaced annotation containers and base containers are nonsensical**

* RESOLVED: Undo previous resolution. Treat replaced elements with an internal ruby display value as if they were inline at used value time

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6000#issuecomment-828601143)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
This replaces the CSSWG resolution from #526.

I believe this matches our current behavior, so no bug needed.
