### ISSUE TITLE
[css-counter-styles] counter-style square symbol (0x25FE) is bad

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#533]
A resolution was made for [csswg-drafts/#6200](https://github.com/w3c/csswg-drafts/issues/6200).

**\[css\-counter\-styles\] counter\-style square symbol \(0x25FE\) is bad**

* RESOLVED: Switch to using 25aa

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6200#issuecomment-828616747)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
Mats's patch ([Part 1](https://phabricator.services.mozilla.com/D111691) in [bug 1542807](https://bugzilla.mozilla.org/show_bug.cgi?id=1542807)) is aligned with the resolution. We don't need a separate bug.
