### ISSUE TITLE
[css-contain] :root/body viewport propagation and containment

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#536]
A resolution was made for [csswg-drafts/#5913](https://github.com/w3c/csswg-drafts/issues/5913).

**\[css\-contain\] :root/body viewport propagation and containment**

* RESOLVED: If there is containment on body or root it stops propagation from body to root

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5913#issuecomment-833119069)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
This is now tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1730763
