### ISSUE TITLE
[css-multicol] Should contained out-of-flow descendants affect column balancing?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#539]
A resolution was made for [csswg-drafts/#6279](https://github.com/w3c/csswg-drafts/issues/6279).

**\[css\-multicol\] Should contained out\-of\-flow descendants affect column balancing?**

* RESOLVED: Add the current interop situation to the spec

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6279#issuecomment-839912199)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
The resolution is the current behavior.
