### ISSUE TITLE
[css-contain] Remove "at-risk" for style containment

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#540]
A resolution was made for [csswg-drafts/#6272](https://github.com/w3c/csswg-drafts/issues/6272).

**\[css\-contain\] Remove "at\-risk" for style containment**

* RESOLVED: Remove at\-risk label for style containment

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6272#issuecomment-839915690)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
This is an editorial resolution. No change needed for implementation.
