### ISSUE TITLE
[css-sizing-4] Only apply contain-intrinsic-size: auto with content-visibility: auto

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#547]
A resolution was made for [csswg-drafts/#6308](https://github.com/w3c/csswg-drafts/issues/6308).

**\[css\-sizing\-4\] Only apply contain\-intrinsic\-size: auto with content\-visibility: auto**

* RESOLVED: only apply contain\-intrinsic\-size: auto with content\-visibility: auto

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6308#issuecomment-848909223)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't implement contain-intrinsic-size yet.

**Comment by smitgd** [comment]
Sorry for spam but need to receive a github email with the subject of this thread to help debug https://bugzilla.mozilla.org/show_bug.cgi?id=171297

Gene Smith
