### ISSUE TITLE
[css-scoping] Handling global name-defining constructs in shadow trees

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#549]
A resolution was made for [csswg-drafts/#1995](https://github.com/w3c/csswg-drafts/issues/1995).

**\[css\-scoping\] Handling global name\-defining constructs in shadow trees**

* RESOLVED: Tentative agreement on the spec text as in the draft. Subject to further review of current interop behavior

[Discussion.](https://github.com/w3c/csswg-drafts/issues/1995#issuecomment-848941922)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
Not actionable just yet.
