### ISSUE TITLE
[css-fonts] Drop bracket matching step from `@font-face` src: line parsing

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#551]
A resolution was made for [csswg-drafts/#6340](https://github.com/w3c/csswg-drafts/issues/6340).

**\[css\-fonts\] Drop bracket matching step from \`@font\-face\` src: line parsing**

* RESOLVED: Parse the value of src throwing out invalid parts like media queries and not like selectors. aka You split on the commas and throw out the pieces you don't understand not the whole thing.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6340#issuecomment-853266812)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
The "RESOLVED" is a quote from other issue, not an actual resolution.
