### ISSUE TITLE
[css-counter-style] overriding symbolic counter styles.

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#552]
A resolution was made for [csswg-drafts/#3584](https://github.com/w3c/csswg-drafts/issues/3584).

**\[css\-counter\-style\] overriding symbolic counter styles.**

* RESOLVED: When you extend a predefined symbolic you are extending the version defined in the spec

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3584#issuecomment-853440806)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by upsuper** [comment]
I think we've implemented this resolution, but not the other in the same issue which was not recorded by the bot:
> Resolved: Make all predefined symbolic counter styles not overwritable

**Comment by dholbert** [comment]
Thanks! I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1714457 for that.
