### ISSUE TITLE
[css-overflow-4] scrollbar-gutter is too complex

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#557]
A resolution was made for [csswg-drafts/#4674](https://github.com/w3c/csswg-drafts/issues/4674).

**\[css\-overflow\-4\] scrollbar\-gutter is too complex**

* RESOLVED: accept the edited changes as described by florian

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4674#issuecomment-857841639)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't implement this feature yet; tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1715112
