### ISSUE TITLE
[css-color-adjust] Re-add `only` to mean "don't auto-adjust me", per WebKit's behavior

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#558]
A resolution was made for [csswg-drafts/#5089](https://github.com/w3c/csswg-drafts/issues/5089).

**\[css\-color\-adjust\] Re\-add \`only\` to mean "don't auto\-adjust me", per WebKit's behavior**

* RESOLVED: Accept changes and add only keyword

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5089#issuecomment-857843575)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
This is a keyword for the "color-scheme" property, which I don't think we implement & is tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1576289
