### ISSUE TITLE
[css-flexbox] clarify whether collapsed flex items influence the flex container's intrinsic main size

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#567]
A resolution was made for [csswg-drafts/#5985](https://github.com/w3c/csswg-drafts/issues/5985).

**\[css\-flexbox\] clarify whether collapsed flex items influence the flex container's intrinsic main size**

* RESOLVED: Accept edits

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5985#issuecomment-862548315)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
Already tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1692366
