### ISSUE TITLE
[css-overflow-4] rename scrollbar-gutter:both

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#582]
A resolution was made for [csswg-drafts/#6349](https://github.com/w3c/csswg-drafts/issues/6349).

**\[css\-overflow\-4\] rename scrollbar\-gutter:both**

* RESOLVED: Rename to 'both\-edges'

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6349#issuecomment-880053625)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
We haven't implemented `scrollbar-butter` yet. [Bug 1715112](https://bugzilla.mozilla.org/show_bug.cgi?id=1715112) tracks it.
