### ISSUE TITLE
[css-scrollbars-1] scrollbar-width should be inherited

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#583]
A resolution was made for [csswg-drafts/#4799](https://github.com/w3c/csswg-drafts/issues/4799).

**\[css\-scrollbars\-1\] scrollbar\-width should be inherited**

* RESOLVED: Close WONTFIX; scrollbar\-width remains non\-inherited

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4799#issuecomment-880055010)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
No need to change our implementation as it matches our current behavior.
