### ISSUE TITLE
[cssom] Publish an updated WD

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#586]
Resolutions were made for [csswg-drafts/#6446](https://github.com/w3c/csswg-drafts/issues/6446).

**\[cssom\] Publish an updated WD**

* RESOLVED: Republish CSS Fonts L4 and L5
* RESOLVED: Republish CSSOM

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6446#issuecomment-884310305)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
No change needed.
