### ISSUE TITLE
[css-fonts] Republish CSS Fonts 4 and 5

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#587]
Resolutions were made for [csswg-drafts/#6462](https://github.com/w3c/csswg-drafts/issues/6462).

**\[css\-fonts\] Republish CSS Fonts 4 and 5**

* RESOLVED: Republish CSS Fonts L4 and L5
* RESOLVED: Republish CSSOM

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6462#issuecomment-884311319)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
No change needed.
