### ISSUE TITLE
[css-flexbox][css-grid] order property definition only mentions "flex items"

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#590]
A resolution was made for [csswg-drafts/#5865](https://github.com/w3c/csswg-drafts/issues/5865).

**\[css\-flexbox\]\[css\-grid\] order property definition only mentions "flex items"**

* RESOLVED: Move order property to Display module

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5865#issuecomment-884323316)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
No change needed.
