### ISSUE TITLE
[css-grid][css-flex] Indefiniteness when sizing grid tracks in a flexible flex item

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#591]
A resolution was made for [csswg-drafts/#4852](https://github.com/w3c/csswg-drafts/issues/4852).

**\[css\-grid\]\[css\-flex\] Indefiniteness when sizing grid tracks in a flexible flex item**

* RESOLVED: close no change, firefox is correct

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4852#issuecomment-884325925)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
> RESOLVED: close no change, firefox is correct

Yay!
