### ISSUE TITLE
[css-contain-2]: Pause media playback in iframes hidden by content-visibility:hidden

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#593]
A resolution was made for [csswg-drafts/#6468](https://github.com/w3c/csswg-drafts/issues/6468).

**\[css\-contain\-2\]: Pause media playback in iframes hidden by content\-visibility:hidden**

* RESOLVED: conceptually play \(invisibly and muted\) any media playback for things that are skipped due to content\-visibility, skipping any events unless queried \(as for animations\)

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6468#issuecomment-887634200)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't implement `content-visibility` yet.
