### ISSUE TITLE
[css-overflow-3] Clarify padding-bottom in overflow content

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#602]
A resolution was made for [csswg-drafts/#129](https://github.com/w3c/csswg-drafts/issues/129).

**\[css\-overflow\-3\] Clarify padding\-bottom in overflow content**

* RESOLVED: Go with Firefox's behavior \- no elements cause the scroll container's inline\-end padding to be used

[Discussion.](https://github.com/w3c/csswg-drafts/issues/129#issuecomment-889481917)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
This issue resolved to match Firefox's current behavior. No need to change.
