### ISSUE TITLE
[css-overflow-3][cssom-view] move scroll-behavior definition?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#604]
A resolution was made for [csswg-drafts/#6482](https://github.com/w3c/csswg-drafts/issues/6482).

**\[css\-overflow\-3\]\[cssom\-view\] move scroll\-behavior definition?**

* RESOLVED: move scroll\-behavior from cssom\-view to css\-overflow\-3

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6482#issuecomment-889491910)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
Editorial
