### ISSUE TITLE
[css-flexbox] should a definite flex-basis always make the main size be definite?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#607]
A resolution was made for [csswg-drafts/#4311](https://github.com/w3c/csswg-drafts/issues/4311).

**\[css\-flexbox\] should a definite flex\-basis always make the main size be definite?**

* RESOLVED: accept proposal and remove note

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4311#issuecomment-889512146)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
This matches the behavior that we already ship, though we can probably take a bug to remove my code-comments about our behavior disagreeing with the spec for the sake of webcompat.

(As of this resolution, the spec has changed to match us and match us & webcompat demands.)

**Comment by dholbert** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1723039
