### ISSUE TITLE
[css-color-3] Publish updated Recommendation with Candidate Corrections

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#610]
A resolution was made for [csswg-drafts/#6486](https://github.com/w3c/csswg-drafts/issues/6486).

**\[css\-color\-3\] Publish updated Recommendation with Candidate Corrections**

* RESOLVED: Publish Colors 3 as updated Recommendation with Candidate Corrections

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6486#issuecomment-893034007)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
No change needed.
