### ISSUE TITLE
[css-overflow-3] Clarify padding in overflow content

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#613]
A resolution was made for [csswg-drafts/#129](https://github.com/w3c/csswg-drafts/issues/129).

**\[css\-overflow\-3\] Clarify padding in overflow content**

* RESOLVED: Undo previous resolution. Explicitly mark as undefined in the draft for now

[Discussion.](https://github.com/w3c/csswg-drafts/issues/129#issuecomment-893052191)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
Tracking in https://bugzilla.mozilla.org/show_bug.cgi?id=1700858

**Comment by dholbert** [comment]
(Should we reopen that bug, perhaps, in light of this resolution-undoing?)

**Comment by aethanyc** [comment]
Yes, I've reopened the bug and adding the discussion and blink's next step.
