### ISSUE TITLE
[css-variables][cssom] Shorthands should serialize as empty string when longhands have variables

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#620]
A resolution was made for [csswg-drafts/#6253](https://github.com/w3c/csswg-drafts/issues/6253).

**\[css\-variables\]\[cssom\] Shorthands should serialize as empty string when longhands have variables**

* RESOLVED: accept edits

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6253#issuecomment-901249422)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
Edits match our behavior.
