### ISSUE TITLE
[css-overflow-3] 'overflow' 2-value syntax is in wrong order

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#629]
A resolution was made for [csswg-drafts/#2988](https://github.com/w3c/csswg-drafts/issues/2988).

**\[css\-overflow\-3\] 'overflow' 2\-value syntax is in wrong order**

* RESOLVED: scroll\-snap\-align and future 2\-axis properties use the logical model

[Discussion.](https://github.com/w3c/csswg-drafts/issues/2988#issuecomment-910878916)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
No action needed here; the proposal was to reorder the values of `scroll-snap-align` to match the legacy physical ordering of `overflow`, but the CSSWG decided against that.
