### ISSUE TITLE
[css-images] Add easing functions to color stops

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#630]
A resolution was made for [csswg-drafts/#1332](https://github.com/w3c/csswg-drafts/issues/1332).

**\[css\-images\] Add easing functions to color stops**

* RESOLVED: Expand the color stop hint grammar with easing functions and define how gradients respond to that

[Discussion.](https://github.com/w3c/csswg-drafts/issues/1332#issuecomment-910891011)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
Just exploratory spec work happening at this point; no actions for us to take yet.
