### ISSUE TITLE
[scroll-animations] TAG feedback: interaction with prefers reduced motion

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#632]
A resolution was made for [csswg-drafts/#5321](https://github.com/w3c/csswg-drafts/issues/5321).

**\[scroll\-animations\] TAG feedback: interaction with prefers reduced motion**

* RESOLVED: We are going to start specifying a no motion at all mode that makes motion inducing animations discrete between keyframes where keyframes are sufficiently separated in time

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5321#issuecomment-910924409)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
This isn't specced yet; no actions needed.
