### ISSUE TITLE
[css-position] What is the behavior of an absolutely-positioned <br>?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#635]
A resolution was made for [csswg-drafts/#5749](https://github.com/w3c/csswg-drafts/issues/5749).

**\[css\-position\] What is the behavior of an absolutely\-positioned &lt;br&gt;?**

* RESOLVED: Close no change: taking BR out of flow removes its effect on the surrounding content, just like every other element

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5749#issuecomment-915386859)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
The resolution matches our current behavior.
