### ISSUE TITLE
[css-multicol-1] New CR?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#639]
A resolution was made for [csswg-drafts/#6612](https://github.com/w3c/csswg-drafts/issues/6612).

**\[css\-multicol\-1\] New CR?**

* RESOLVED: Transition css\-multicol\-1 back to CR

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6612#issuecomment-920189454)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
No change needed.
