### ISSUE TITLE
[css-box-3] Should margin-trim apply to flex or grid containers?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#643]
A resolution was made for [csswg-drafts/#3255](https://github.com/w3c/csswg-drafts/issues/3255).

**\[css\-box\-3\] Should margin\-trim apply to flex or grid containers?**

* RESOLVED: margin\-trim applies to flex and grid containers also

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3255#issuecomment-925074713)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't implement this property yet (nor does any engine at this point, according to https://caniuse.com/?search=margin-trim )
