### ISSUE TITLE
[css-box-4] Switch margin-trim to boolean indicating sides rather than types of boxes to trim

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#644]
A resolution was made for [csswg-drafts/#6643](https://github.com/w3c/csswg-drafts/issues/6643).

**\[css\-box\-4\] Switch margin\-trim to boolean indicating sides rather than types of boxes to trim**

* RESOLVED: margin\-trim determines which sides to apply to as described in \#6643

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6643#issuecomment-925102030)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't yet implement this feature. It's tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1506241
