### ISSUE TITLE
[css-flexbox-1][css-sizing-3] Definiteness of `min-height: min-content`

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#660]
A resolution was made for [csswg-drafts/#6457](https://github.com/w3c/csswg-drafts/issues/6457).

**\[css\-flexbox\-1\]\[css\-sizing\-3\] Definiteness of \`min\-height: min\-content\`**

* RESOLVED: min\-height:auto just has special behavior that allows child %s to still resolve, and it's not a precedent to apply to all the other content\-based keywords. \(Thus, we'll remove, or possibly keep\-but\-reverse, the note that's currently in the spec.\)

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6457#issuecomment-937330433)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't honor `min-height:min-content` etc. yet; for now, we just treat them as the initial value (`auto`) which is what the spec originally required (that changed in https://github.com/w3c/csswg-drafts/issues/3973#issuecomment-705663905)

Once we give them special content-based treatment, we'll need to take this resolution into consideration.

**Comment by dholbert** [comment]
I added a note on https://bugzilla.mozilla.org/show_bug.cgi?id=1672559 to remind us about this.

**Comment by yisibl** [comment]
Chrome implemented it a while ago. https://issues.chromium.org/issues/40151761#comment12
