### ISSUE TITLE
[css-fonts-5] How to add new generic font families

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#667]
A resolution was made for [csswg-drafts/#6770](https://github.com/w3c/csswg-drafts/issues/6770).

**\[css\-fonts\-5\] How to add new generic font families**

* RESOLVED: serif, sanserif, and monospace must match, all other generics should match if appropriate.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6770#issuecomment-953164409)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
Dupe of #147 .
