### ISSUE TITLE
[css-color-4] Defer @color-profile to L5

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#682]
A resolution was made for [csswg-drafts/#6765](https://github.com/w3c/csswg-drafts/issues/6765).

**\[css\-color\-4\] Defer @color\-profile to L5**

* RESOLVED: Move @color\-profile and device\-cmyk\(\) to L5

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6765#issuecomment-965592183)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
Editorial only
