### ISSUE TITLE
[css-position] Behaviour of semi-replaced elements.

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#688]
A resolution was made for [csswg-drafts/#6789](https://github.com/w3c/csswg-drafts/issues/6789).

**\[css\-position\] Behaviour of semi\-replaced elements.**

* RESOLVED: Semi\-replaced elements stretch in both directions in abspos

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6789#issuecomment-971805915)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
This is covered by https://bugzilla.mozilla.org/show_bug.cgi?id=1740580
