### ISSUE TITLE
[css-images] Layout of iframes with content intrinsic sizing that does not match the <iframe>

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#695]
Resolutions were made for [csswg-drafts/#6817](https://github.com/w3c/csswg-drafts/issues/6817).

**\[css\-images\] Layout of iframes with content intrinsic sizing that does not match the &lt;iframe&gt;**

* RESOLVED: object\-fit affects the rendering of iframes with expressed intrinsic sizes
* RESOLVED: object\-position applies to iframes in the above case as well

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6817#issuecomment-984196258)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
Per the csswg discussion, this is only relevant once we've got some additional features (iframes [with content-based intrinsic sizes](https://github.com/w3c/csswg-drafts/issues/1771), and potentially also for "fenced" iframes, another proposal that we don't implement at this point).  This CSSWG resolution would inform the implementation of those features. So, no bug needed for the resolution at this point.
