### ISSUE TITLE
CSS snapshot 2021

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#696]
Resolutions were made for [csswg-drafts/#6243](https://github.com/w3c/csswg-drafts/issues/6243).

**CSS snapshot 2021**

* RESOLVED: Transforms 2 to "rough interop"
* RESOLVED: other specs as proposed, except for Color 4 and overscroll\-behavior
* RESOLVED: Publish Snapshot 2021 as a NOTE after edits

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6243#issuecomment-988962809)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
Editorial only.
