### ISSUE TITLE
[css-fonts-4] Naming font-technology() supports function

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#697]
A resolution was made for [csswg-drafts/#6791](https://github.com/w3c/csswg-drafts/issues/6791).

**\[css\-fonts\-4\] Naming font\-technology\(\) supports function**

* RESOLVED: font\-tech\(\) and technology\(\)

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6791#issuecomment-988991249)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by svgeesus** [comment]
Note that an IRC edit was not picked up, the actual resolution was 

> RESOLVED: font-tech() and tech()

(Discussed just now on CSSWG call and minutes edited)
