### ISSUE TITLE
[cssom] should custom properties be exposed on computed style declarations?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#7]
A resolution was made for [csswg-drafts/#1316](https://github.com./w3c/csswg-drafts/issues/1316).

**\[cssom\] should custom properties be exposed on computed style declarations?**

* RESOLVED: non\-initial custom properties should be exposed on computed style objects, open a new issue about defining order

[Discussion.](https://github.com./w3c/csswg-drafts/issues/1316#issuecomment-486332571)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
We already expose custom properties through getPropertyValue etc. on computed style objects.
