### ISSUE TITLE
Updated WD of CSS Color 4 (for wide review before CR) and CSS Color 5

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#700]
A resolution was made for [csswg-drafts/#6854](https://github.com/w3c/csswg-drafts/issues/6854).

**Updated WD of CSS Color 4 \(for wide review before CR\) and CSS Color 5**

* RESOLVED: Publish Color 4 and Color 5 as WD

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6854#issuecomment-989059174)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
Editorial only.
