### ISSUE TITLE
[css-cascade-6] First Public Working Draft of `@scope`

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#701]
A resolution was made for [csswg-drafts/#6865](https://github.com/w3c/csswg-drafts/issues/6865).

**\[css\-cascade\-6\] First Public Working Draft of \`@scope\`**

* RESOLVED: FPWD Cascade 6

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6865#issuecomment-989060825)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
Editorial only.
