### ISSUE TITLE
[mediaqueries] length units in video-* media features.

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#702]
A resolution was made for [csswg-drafts/#5044](https://github.com/w3c/csswg-drafts/issues/5044).

**\[mediaqueries\] length units in video\-\* media features.**

* RESOLVED: Drop video\-width/height/resolution media queries

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5044#issuecomment-995006227)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
I suspect we never supported these in the first place; I don't see any hits in our source for `video-width`, `video-height`, or `video-resolution`:
https://searchfox.org/mozilla-central/search?q=video-width
https://searchfox.org/mozilla-central/search?q=video-height
https://searchfox.org/mozilla-central/search?q=video-resolution
