### ISSUE TITLE
[css-flexbox] Flexbox alignment and fragmentation

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#708]
Resolutions were made for [csswg-drafts/#6812](https://github.com/w3c/csswg-drafts/issues/6812).

**\[css\-flexbox\] Flexbox alignment and fragmentation**

* RESOLVED: We will spec that grid, flex, and table fragmentation align globally before fragments are created
* RESOLVED: we will not truncate margins at any break when aligning globally for fragmentation

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6812#issuecomment-1006181635)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
The resolution matches Firefox's existing behavior, as far as I know.

(and Blink folks are going to add WPTs as they implement the new behavior, so if there's anything for us to do, hopefully we'll find out when those tests get added. :))
