### ISSUE TITLE
[css-values-4] Validity of generic interpolation function mix()

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#709]
A resolution was made for [csswg-drafts/#6700](https://github.com/w3c/csswg-drafts/issues/6700).

**\[css\-values\-4\] Validity of generic interpolation function mix\(\)**

* RESOLVED: The mix interpolation function will only be used for top\-level values with various discussed caveats. mix is the name of the top level interpolation

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6700#issuecomment-1006186578)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't implement mix() yet, so this resolution doesn't need a specific bug.

I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1748924 on the mix() function itself, since I don't think we had a tracking bug for that feature yet.
