### ISSUE TITLE
[cssom-view] Needs more details for `offsetWidth` and `offsetHeight`

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#710]
A resolution was made for [csswg-drafts/#6588](https://github.com/w3c/csswg-drafts/issues/6588).

**\[cssom\-view\] Needs more details for \`offsetWidth\` and \`offsetHeight\`**

* RESOLVED: When an inline box is split by a block box, offsetWidth and offsetHeight will include dimensions of block box

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6588#issuecomment-1006198491)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
The resolution is in favor of existing Gecko behavior.  So, no bug needed.

(I initially thought it was also in favor of a WebKit-specific quirk, and I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1749657 on that, but then I realized I was probably-misunderstanding, per https://github.com/w3c/csswg-drafts/issues/6588#issuecomment-1010695486 )
