### ISSUE TITLE
CSS Color 3: Proposed Changes

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#712]
A resolution was made for [csswg-drafts/#6910](https://github.com/w3c/csswg-drafts/issues/6910).

**CSS Color 3: Proposed Changes**

* RESOLVED: Republish CSS Color 3 REC as editorial update

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6910#issuecomment-1011274166)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
Editorial update only.
