### ISSUE TITLE
[css-text-4] Is hyphenate-character stable enough to ship?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#721]
A resolution was made for [csswg-drafts/#6887](https://github.com/w3c/csswg-drafts/issues/6887).

**\[css\-text\-4\] Is hyphenate\-character stable enough to ship?**

* RESOLVED: hyphenate\-character is shippable; we'll add it to the Snapshot 2022 list of exceptions

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6887#issuecomment-1016667299)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by jfkthame** [comment]
The WG agreed it's ok to ship this, so let's have a bug to take it out from behind the Nightly flag.

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1751024
