### ISSUE TITLE
[css-values-4] Allow an inline way to do "first value that's supported"

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#726]
Resolutions were made for [csswg-drafts/#5055](https://github.com/w3c/csswg-drafts/issues/5055).

**\[css\-values\-4\] Allow an inline way to do "first value that's supported"**

* RESOLVED: add \`first\-valid\` and please add an issue to bikeshed the name once we better understnad the scope
* RESOLVED: add \`first\-valid\` and please add an issue to bikeshed the name once we better understand the scope

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5055#issuecomment-1022425917)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by emilio** [comment]
Once there's a spec we can file a bug for this.
