### ISSUE TITLE
[css-contain-3] Spec syntax for size queries

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#727]
A resolution was made for [csswg-drafts/#6870](https://github.com/w3c/csswg-drafts/issues/6870).

**\[css\-contain\-3\] Spec syntax for size queries**

* RESOLVED: drop the function syntax for querying sizes, but keep the function syntax for querying styles

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6870#issuecomment-1022430911)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
This was a change to a container-query feature that we don't currently implement ( https://www.w3.org/TR/css-contain-3/#container-rule )
