### ISSUE TITLE
[css-flexbox] Percentage height resolution of children of flex items with indefinite flex basis

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#728]
A resolution was made for [csswg-drafts/#6822](https://github.com/w3c/csswg-drafts/issues/6822).

**\[css\-flexbox\] Percentage height resolution of children of flex items with indefinite flex basis**

* RESOLVED: Reject the proposed change but clarify the specification; we invite Serifo to comment further if they have objections to this resolution

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6822#issuecomment-1022447206)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
Firefox implements the correct behavior. No change needed.
