### ISSUE TITLE
[css-color] Support all existing (non-legacy?) formats in color()?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#741]
A resolution was made for [csswg-drafts/#6741](https://github.com/w3c/csswg-drafts/issues/6741).

**\[css\-color\] Support all existing \(non\-legacy?\) formats in color\(\)?**

* RESOLVED: Will add this to the color\-4 module, after forking to a new issue

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6741#issuecomment-1041893440)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
color() is not yet implemented; that's https://bugzilla.mozilla.org/show_bug.cgi?id=1128204
