### ISSUE TITLE
[css-images-4] Proposal to allow replaced elements to paint outside of their bounds

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#750]
A resolution was made for [csswg-drafts/#7058](https://github.com/w3c/csswg-drafts/issues/7058).

**\[css\-images\-4\] Proposal to allow replaced elements to paint outside of their bounds**

* RESOLVED: We add to Images 5 these 2 properties, object\-viewbox and object\-overflow. 1 is bool about hidden and visible and the other is eq. of SVG viewbox. We would try and create a mapping between svg and new property. New property would take inset and xywh so there's 2 ways to spec size

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7058#issuecomment-1057543300)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We can file a bug for this once there's spec text.

**Comment by khushalsagar** [comment]
Heads up, I've filed an RFP with the landed spec here : https://github.com/mozilla/standards-positions/issues/626.
