### ISSUE TITLE
[css-flexbox] Multi-line column flexbox fragmentation

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#751]
Resolutions were made for [csswg-drafts/#6855](https://github.com/w3c/csswg-drafts/issues/6855).

**\[css\-flexbox\] Multi\-line column flexbox fragmentation**

* RESOLVED: Treat items as not monolithic
* RESOLVED: update fragmentation rules to flexbox to handle multiline independently

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6855#issuecomment-1057547095)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
I believe the resolution is leaning toward the Firefox's behavior, and we don't have to change the behavior.
