### ISSUE TITLE
[css-overscroll] Whether to move position:fixed elements during overscrolling

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#757]
Resolutions were made for [csswg-drafts/#6299](https://github.com/w3c/csswg-drafts/issues/6299).

**\[css\-overscroll\] Whether to move position:fixed elements during overscrolling**

* RESOLVED: fixed\-position elements whose scroller is not their containing block do not participate in overscroll
* RESOLVED: the former statement also applies to sticky element when stuck

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6299#issuecomment-1076552713)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
@hiikezoe would know for sure I think, but I suspect we need a bug here.  (Based on the csswg issue, it looks like we'll need to [partially?] revert https://bugzilla.mozilla.org/show_bug.cgi?id=1704503 )

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1761049

**Comment by theres-waldo** [comment]
> @hiikezoe would know for sure I think, but I suspect we need a bug here. (Based on the csswg issue, it looks like we'll need to [partially?] revert https://bugzilla.mozilla.org/show_bug.cgi?id=1704503 )

I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1760368 for this a few days ago
