### ISSUE TITLE
[css-images-4][css-overflow-3] How do `object-overflow` and `object-view-box` interact with `overflow` and `overflow-clip-margin`?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#767]
A resolution was made for [csswg-drafts/#7144](https://github.com/w3c/csswg-drafts/issues/7144).

**\[css\-images\-4\]\[css\-overflow\-3\] How do \`object\-overflow\` and \`object\-view\-box\` interact with \`overflow\` and \`overflow\-clip\-margin\`?**

* RESOLVED: Add this path forward to the spec with a note linking back to this issue

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7144#issuecomment-1090933632)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1779332 on this.
