### ISSUE TITLE
[css-background-4] Issues with listifying border-color

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#780]
A resolution was made for [csswg-drafts/#2532](https://github.com/w3c/csswg-drafts/issues/2532).

**\[css\-background\-4\] Issues with listifying border\-color**

* RESOLVED: Remove &lt;1d\-image&gt; from &lt;image&gt; for now, open a separate issue to discuss it

[Discussion.](https://github.com/w3c/csswg-drafts/issues/2532#issuecomment-1111207894)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
Pretty sure this isn't something we implement anyway. (I don't see hits for `1d-image`, or CSS-related hits for `stripe(`, in a searchfox search).
