### ISSUE TITLE
[selectors-4] List of -webkit- legacy aliases

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#792]
A resolution was made for [csswg-drafts/#7257](https://github.com/w3c/csswg-drafts/issues/7257).

**\[selectors\-4\] List of \-webkit\- legacy aliases**

* RESOLVED: Add :\-webkit\-autofill in an appendix of selectors 4.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7257#issuecomment-1130263505)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
Looks like this was just updating a spec to match reality; and it looks like we support this selector (and there's a WPT test for it) per https://searchfox.org/mozilla-central/search?q=webkit-autofill&path=
