### ISSUE TITLE
[css-overflow] Overflow propagation when the element propagated from is display: none

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#8]
A resolution was made for [csswg-drafts/#3779](https://github.com./w3c/csswg-drafts/issues/3779).

**\[css\-overflow\] Overflow propagation when the element propagated from is display: none**

* RESOLVED: Do not propagate any style from display:none HTML or Body

[Discussion.](https://github.com./w3c/csswg-drafts/issues/3779#issuecomment-481762912)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
This was already done in https://bugzilla.mozilla.org/show_bug.cgi?id=1540220.
