### ISSUE TITLE
[scroll-animations-1] Support setting start and end time on scroll timeline.

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#802]
A resolution was made for [csswg-drafts/#7296](https://github.com/w3c/csswg-drafts/issues/7296).

**\[scroll\-animations\-1\] Support setting start and end time on scroll timeline.**

* RESOLVED: Close this with no change

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7296#issuecomment-1144242836)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
No change needed
