### ISSUE TITLE
[scroll-animations-1] Rethinking timeline-phase

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#803]
A resolution was made for [csswg-drafts/#7240](https://github.com/w3c/csswg-drafts/issues/7240).

**\[scroll\-animations\-1\] Rethinking timeline\-phase**

* RESOLVED: Remove phase from the animation timeline IDL and remove the before and after timeline\-phases

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7240#issuecomment-1144244531)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
We don't support timeline-phase so we don't need a bug to remove them.
