### ISSUE TITLE
[css-text] text-align: match-parent on the root element with direction: rtl doesn't match browsers

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#806]
A resolution was made for [csswg-drafts/#6542](https://github.com/w3c/csswg-drafts/issues/6542).

**\[css\-text\] text\-align: match\-parent on the root element with direction: rtl doesn't match browsers**

* RESOLVED: text\-align: match\-parent computes to 'start' on the root element

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6542#issuecomment-1150166992)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
It looks like the resolution agrees with what we (and other browsers) already do. --> No bug needed.
