### ISSUE TITLE
[cssom-view] Rename Element.isVisible to Element.isHidden?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#818]
A resolution was made for [csswg-drafts/#7317](https://github.com/w3c/csswg-drafts/issues/7317).

**\[cssom\-view\] Rename Element.isVisible to Element.isHidden?**

* RESOLVED: Rename to checkVisibility\(\)

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7317#issuecomment-1170204212)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
I added a comment on https://bugzilla.mozilla.org/show_bug.cgi?id=1777293 to reflect the new name.
