### ISSUE TITLE
[css-overflow] overflow-clip-margin might want to set different boxes in the block and inline axes.

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#822]
A resolution was made for [csswg-drafts/#7245](https://github.com/w3c/csswg-drafts/issues/7245).

**\[css\-overflow\] overflow\-clip\-margin might want to set different boxes in the block and inline axes.**

* RESOLVED: Add overflow\-clip\-margin\-inline, \-block, and the full set of properties

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7245#issuecomment-1176865109)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
This is already covered by https://bugzilla.mozilla.org/show_bug.cgi?id=1661582 basically.
