### ISSUE TITLE
[css-ui] `revert-layer` rolling back to author origin should disable native appearance

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#826]
A resolution was made for [csswg-drafts/#7239](https://github.com/w3c/csswg-drafts/issues/7239).

**\[css\-ui\] \`revert\-layer\` rolling back to author origin should disable native appearance**

* RESOLVED: For properties that disable native appearance, do all the reverting, take into account the origin of the final cascaded value

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7239#issuecomment-1183460954)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
Quoting the discussion, oriol (presenting the issue) said "... all implementations already behave like this", " so proposal is to align with implementations"

It looks (?) like that's what the resolution was in favor of, so I think we can close this.

@emilio: if I'm misunderstanding, please file a bug if necessary - thanks! :)
