### ISSUE TITLE
[css-mediaqueries] Should prefers-color-scheme in SVG images be context-dependent?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#827]
A resolution was made for [csswg-drafts/#7213](https://github.com/w3c/csswg-drafts/issues/7213).

**\[css\-mediaqueries\] Should prefers\-color\-scheme in SVG images be context\-dependent?**

* RESOLVED: prefers\-color\-scheme in SVG rendered in secure animated mode is context\-dependent

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7213#issuecomment-1183468735)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
@emilio filed & fixed https://bugzilla.mozilla.org/show_bug.cgi?id=1779457 to address this.
