### ISSUE TITLE
[scroll-animations-1] currentTime when scroll range is 0?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#830]
A resolution was made for [csswg-drafts/#7401](https://github.com/w3c/csswg-drafts/issues/7401).

**\[scroll\-animations\-1\] currentTime when scroll range is 0?**

* RESOLVED: In the absence of scroll range, timeline becomes inactive

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7401#issuecomment-1190502162)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
@boris, do you know if we need a bug to match this spec-change?  Or does this already match what we do via your scroll-linked animations work at this point?

**Comment by dholbert** [comment]
er sorry, meant to tag @BorisChiou .  (Apologies other boris; github username-autocomplete got the better of me.

**Comment by BorisChiou** [comment]
Yes we need one for this.

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1780865
