### ISSUE TITLE
[css-overflow-3] shorten name of overflow-clip-margin?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#831]
A resolution was made for [csswg-drafts/#7464](https://github.com/w3c/csswg-drafts/issues/7464).

**\[css\-overflow\-3\] shorten name of overflow\-clip\-margin?**

* RESOLVED: Close no change.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7464#issuecomment-1196961897)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
No change to the spec.
