### ISSUE TITLE
[selectors-4] Disallow pseudo-elements inside :has()

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#832]
A resolution was made for [csswg-drafts/#7463](https://github.com/w3c/csswg-drafts/issues/7463).

**\[selectors\-4\] Disallow pseudo\-elements inside :has\(\)**

* RESOLVED: Disallow all current pseudo\-elements inside of :has\(\), allow future pseudo\-elements to define that they are valid if useful/possible.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7463#issuecomment-1196971909)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We haven't implemented `:has` yet (beyond some basic parsing); https://bugzilla.mozilla.org/show_bug.cgi?id=418039 is the tracking bug for the feature.  So, we probably don't need a dedicated bug for this spec change.

I'll add a note on bug 418039 mentioning this working-group resolution, in case it hasn't made it into the spec yet when we start implementing.
