### ISSUE TITLE
[css-sizing-4] Only apply contain-intrinsic-size: auto with content-visibility: auto

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#834]
A resolution was made for [csswg-drafts/#6308](https://github.com/w3c/csswg-drafts/issues/6308).

**\[css\-sizing\-4\] Only apply contain\-intrinsic\-size: auto with content\-visibility: auto**

* RESOLVED: Drop the "not relevant to the user" condition from c\-i\-s:auto

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6308#issuecomment-1196994821)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
@Loirooriol has been working on this contain-intrinsic-size feature in Gecko (in dependencies of https://bugzilla.mozilla.org/show_bug.cgi?id=1597529 ) and has landed some parts already.

Oriol, do we need to make any changes in response to this resolution? (Does the code that you've landed so far have any "relevant to the user"-consideration that we need to remove now?)

If no implementation changes are needed for this resolution, we can just close this issue.

**Comment by Loirooriol** [comment]
No, I haven't landed the code that will be affected by the resolution. Actually I think there is no notion of "relevant to the user" yet, needs to be added by `content-visibility: auto`.
