### ISSUE TITLE
[scroll-animations-1] Should range of ViewTimeline be clamped to scrollable range?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#835]
A resolution was made for [csswg-drafts/#7432](https://github.com/w3c/csswg-drafts/issues/7432).

**\[scroll\-animations\-1\] Should range of ViewTimeline be clamped to scrollable range?**

* RESOLVED: ViewTimeline progress is not clamped by scrollable range

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7432#issuecomment-1197024321)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
ViewTimeline is not support for now and this decision doesn't change the spec proposal.
