### ISSUE TITLE
[css-sizing] How does 0x0 size affect last remembered size?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#842]
Resolutions were made for [csswg-drafts/#7539](https://github.com/w3c/csswg-drafts/issues/7539).

**\[css\-sizing\] How does 0x0 size affect last remembered size?**

* RESOLVED: 0x0 is not special wrt ResizeObserver or c\-i\-s
* RESOLVED: Replace ResizeObserver editors with Oriol and Emilio

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7539#issuecomment-1202608735)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by Loirooriol** [comment]
For `contain-intrinsic-size` already done in https://bugzilla.mozilla.org/show_bug.cgi?id=1781046.
`ResizeObserver` in general handled in #875
