### ISSUE TITLE
[css-sizing] Should last remembered size be removed if the element is removed from the document?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#843]
A resolution was made for [csswg-drafts/#7532](https://github.com/w3c/csswg-drafts/issues/7532).

**\[css\-sizing\] Should last remembered size be removed if the element is removed from the document?**

* RESOLVED: At ResizeObserver time, forget an element's last remembered size if it is currently out of the document

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7532#issuecomment-1202640447)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by Loirooriol** [comment]
Already taken into account in https://phabricator.services.mozilla.com/D152642
