### ISSUE TITLE
[css-sizing] Is the last remembered size recorded if there is size containment in a single axis?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#844]
A resolution was made for [csswg-drafts/#7529](https://github.com/w3c/csswg-drafts/issues/7529).

**\[css\-sizing\] Is the last remembered size recorded if there is size containment in a single axis?**

* RESOLVED: "last remembered size" is tracked for the two axises independently \(in case of containment in one axis\), and can be invoked independently \(with c\-i\-s:auto in one axis\)

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7529#issuecomment-1202656520)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by Loirooriol** [comment]
Already taken into account in https://bugzilla.mozilla.org/show_bug.cgi?id=1781046 and https://phabricator.services.mozilla.com/D152642
