### ISSUE TITLE
[css-sizing] Clarify contain-intrinsic-size with multicolumn/grid

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#845]
A resolution was made for [csswg-drafts/#7520](https://github.com/w3c/csswg-drafts/issues/7520).

**\[css\-sizing\] Clarify contain\-intrinsic\-size with multicolumn/grid**

* RESOLVED: Clarify that setting c\-i\-s to a size overrides the content size, even if there is other sizing info such as grid column widths

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7520#issuecomment-1202700898)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by Loirooriol** [comment]
Done in https://bugzilla.mozilla.org/show_bug.cgi?id=1783953 and https://bugzilla.mozilla.org/show_bug.cgi?id=1782297

Proper `contain-intrinsic-size: none` for grid is tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1488878
