### ISSUE TITLE
[css-sizing] Clarify how contain-intrinsic-size affects size containment algorithm

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#846]
A resolution was made for [csswg-drafts/#7519](https://github.com/w3c/csswg-drafts/issues/7519).

**\[css\-sizing\] Clarify how contain\-intrinsic\-size affects size containment algorithm**

* RESOLVED: contain\-intrinsic\-size size is used as the natural sizes of replaced elements \(but does not set the aspect ratio\)

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7519#issuecomment-1202721367)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by Loirooriol** [comment]
This can be closes, already done.
