### ISSUE TITLE
[css-sizing] What happens with the last remembered size if there is no principal box?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#847]
A resolution was made for [csswg-drafts/#7527](https://github.com/w3c/csswg-drafts/issues/7527).

**\[css\-sizing\] What happens with the last remembered size if there is no principal box?**

* RESOLVED: If an element doesn't have a principal box, we do not record a last remembered size

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7527#issuecomment-1202748701)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by Loirooriol** [comment]
This can be closed, I'm taking the resolution into account for https://phabricator.services.mozilla.com/D152642

**Comment by dholbert** [comment]
Thanks!
