### ISSUE TITLE
[scroll-animations-1] Scope of Named Timelines

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#859]
Resolutions were made for [csswg-drafts/#7047](https://github.com/w3c/csswg-drafts/issues/7047).

**\[scroll\-animations\-1\] Scope of Named Timelines**

* RESOLVED: scope of named timelines is across flattened tree
* RESOLVED: timeline search looks at preceding siblings and ancestors, recursively

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7047#issuecomment-1203984802)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
Need a bug because the current implementation doesn't use the flatten tree.

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1782995
