### ISSUE TITLE
[scroll-animations-1] Do we need container-name references?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#860]
A resolution was made for [csswg-drafts/#7046](https://github.com/w3c/csswg-drafts/issues/7046).

**\[scroll\-animations\-1\] Do we need container\-name references?**

* RESOLVED: remove the container name argument from the scroll\(\) function

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7046#issuecomment-1204014693)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
We don't need a bug for this because we didn't implement this argument in scroll() ([code](https://searchfox.org/mozilla-central/rev/560bbebd595cf2f6a9861f3f67dd0739f4c4c559/servo/components/style/values/specified/box.rs#773-781)). Just need to remove the comment.
