### ISSUE TITLE
[scroll-animations-1] Entry/Exit Transitions for View Timeline effects

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#861]
A resolution was made for [csswg-drafts/#7044](https://github.com/w3c/csswg-drafts/issues/7044).

**\[scroll\-animations\-1\] Entry/Exit Transitions for View Timeline effects**

* RESOLVED: Accept all of fantasai's bullet points from her summary, except for the keyword\+% in @keyframes

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7044#issuecomment-1204032112)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
Close this because we don't need a separate bug for this now. (I will file new ones based on our implementation when I start to work on view-timeline.)
