### ISSUE TITLE
[scroll-animations-1] Unifying ScrollTimeline and ViewTimeline

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#863]
A resolution was made for [csswg-drafts/#7462](https://github.com/w3c/csswg-drafts/issues/7462).

**\[scroll\-animations\-1\] Unifying ScrollTimeline and ViewTimeline**

* RESOLVED: close no change

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7462#issuecomment-1204083442)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
no change needed
