### ISSUE TITLE
[scroll-animations-1] view timeline insets

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#864]
A resolution was made for [csswg-drafts/#7243](https://github.com/w3c/csswg-drafts/issues/7243).

**\[scroll\-animations\-1\] view timeline insets**

* RESOLVED: view\-timeline\-inset takes a comma\-separated list of 1 or 2 values, being autos or length\-percentage

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7243#issuecomment-1204110117)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
No extra bug is needed
