### ISSUE TITLE
[scroll-animations-1] Interaction of content-visibility: auto and ScrollTimeline.currentTime

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#865]
A resolution was made for [csswg-drafts/#7545](https://github.com/w3c/csswg-drafts/issues/7545).

**\[scroll\-animations\-1\] Interaction of content\-visibility: auto and ScrollTimeline.currentTime**

* RESOLVED: close no change

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7545#issuecomment-1204119228)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
No change is needed.
