### ISSUE TITLE
[css-sizing-4] aspect-ratio via width and height attributes doesn't work for <video>

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#869]
A resolution was made for [csswg-drafts/#7524](https://github.com/w3c/csswg-drafts/issues/7524).

**\[css\-sizing\-4\] aspect\-ratio via width and height attributes doesn't work for &lt;video&gt;**

* RESOLVED: Clarify that aspect\-ratio:auto doesn't pull aspect ratio from the default object size, it can only pull from an actual loaded resource

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7524#issuecomment-1204462924)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1783069
