### ISSUE TITLE
[css-sizing-4] Clarify spec about when elements are allowed to not have a last remembered size

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#872]
A resolution was made for [csswg-drafts/#6220](https://github.com/w3c/csswg-drafts/issues/6220).

**\[css\-sizing\-4\] Clarify spec about when elements are allowed to not have a last remembered size**

* RESOLVED: When laying out an element, if contain\-intrinsic\-size is not auto, remove last\-remembered\-size immediately

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6220#issuecomment-1218254965)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
I think @loirooriol is working on this already; likely no specific bug needed here for this spec change.

(Oriol: if I'm misunderstanding, please do file a bug etc. as-needed. :))

**Comment by Loirooriol** [comment]
Yes, I have updated https://phabricator.services.mozilla.com/D152642 to reflect the resolution
