### ISSUE TITLE
[css-sizing] Is last remembered size logical or physical?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#873]
A resolution was made for [csswg-drafts/#7564](https://github.com/w3c/csswg-drafts/issues/7564).

**\[css\-sizing\] Is last remembered size logical or physical?**

* RESOLVED: Last remembered size is the logical size, not the physical size

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7564#issuecomment-1218258109)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
@loirooriol said in the discussion that his current patches already behave in accordance with the resolution here.
