### ISSUE TITLE
[css-sizing][css-contain] Are intrinsic sizing keywords definite with size containment?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#874]
A resolution was made for [csswg-drafts/#7206](https://github.com/w3c/csswg-drafts/issues/7206).

**\[css\-sizing\]\[css\-contain\] Are intrinsic sizing keywords definite with size containment?**

* RESOLVED: no change to specified behavior

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7206#issuecomment-1218266195)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
no change --> no bug needed, I think.
