### ISSUE TITLE
[css-flexbox] `align-content: stretch` for abspos children of flex containers should align with browser behavior.

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#877]
Resolutions were made for [csswg-drafts/#7596](https://github.com/w3c/csswg-drafts/issues/7596).

**\[css\-flexbox\] \`align\-content: stretch\` for abspos children of flex containers should align with browser behavior.**

* RESOLVED: ignore the effect of align\-content properties on absolutely positioned elements in flex
* RESOLVED: open an issue on justify\-content

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7596#issuecomment-1225952646)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
We are going to change our behavior to match the spec in https://bugzilla.mozilla.org/show_bug.cgi?id=1786910
