### ISSUE TITLE
[css-sizing] Define precise timing for setting last remembered size?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#885]
A resolution was made for [csswg-drafts/#7659](https://github.com/w3c/csswg-drafts/issues/7659).

**\[css\-sizing\] Define precise timing for setting last remembered size?**

* RESOLVED: Accept Oriol's proposal to record last remembered size first before ResizeObserver callbacks

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7659#issuecomment-1240013358)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by Loirooriol** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1789855
