### ISSUE TITLE
[css-sizing] Last remembered size for non-atomic inlines?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#886]
A resolution was made for [csswg-drafts/#7606](https://github.com/w3c/csswg-drafts/issues/7606).

**\[css\-sizing\] Last remembered size for non\-atomic inlines?**

* RESOLVED: display:inline doesn't record a size

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7606#issuecomment-1240015961)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by Loirooriol** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1789754
