### ISSUE TITLE
[css-align-3] Baselines need to be defined on fieldsets.

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#895]
A resolution was made for [csswg-drafts/#7656](https://github.com/w3c/csswg-drafts/issues/7656).

**\[css\-align\-3\] Baselines need to be defined on fieldsets.**

* RESOLVED: default first and last baselines to be the fieldset content's

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7656#issuecomment-1248617134)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
[Bug 1821559](https://bugzilla.mozilla.org/show_bug.cgi?id=1821559) will change the implementation.
