### ISSUE TITLE
[css-font-loading-3] Lots of edits since 2014 /TR, republish?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#915]
Resolutions were made for [csswg-drafts/#7065](https://github.com/w3c/csswg-drafts/issues/7065).

**\[css\-font\-loading\-3\] Lots of edits since 2014 /TR, republish?**

* RESOLVED: Republish css\-font\-loading\-3 once the Changes section is up to date
* RESOLVED: ... as a WD

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7065#issuecomment-1249929485)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
No change needed.
