### ISSUE TITLE
[css-backgrounds] Are the rules for interactions of transforms and backgrounds on the root element what we want?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#919]
Resolutions were made for [csswg-drafts/#6683](https://github.com/w3c/csswg-drafts/issues/6683).

**\[css\-backgrounds\] Are the rules for interactions of transforms and backgrounds on the root element what we want?**

* RESOLVED: Always ignore transforms on backgrounds of the root element
* RESOLVED: Always ignore transforms on backgrounds that propagate to canvas

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6683#issuecomment-1269092125)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
From what I could tell, it sounded like the resolution matched our existing behavior. (From the initial comment on the spec issue, "Gecko never honors the transform", which is essentially what the CSSWG resolved as the update to the spec.)
