### ISSUE TITLE
[css-text-4] text-spacing: trim-end is better than allow-end for the normal value

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#925]
A resolution was made for [csswg-drafts/#7055](https://github.com/w3c/csswg-drafts/issues/7055).

**\[css\-text\-4\] text\-spacing: trim\-end is better than allow\-end for the normal value**

* RESOLVED: Incorporate trim\-end behavior into the normal keyword

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7055#issuecomment-1276421476)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
We don't support `text-spacing` at all right now; that's tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=289130 . I'll add a note there.
