### ISSUE TITLE
[css-grid-2] How to properly accommodate margin/border/padding of a subgrid with no item on the edges

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#942]
A resolution was made for [csswg-drafts/#7465](https://github.com/w3c/csswg-drafts/issues/7465).

**\[css\-grid\-2\] How to properly accommodate margin/border/padding of a subgrid with no item on the edges**

* RESOLVED: Change the spec to simplify this sizing and figure out what tests we need

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7465#issuecomment-1301484688)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
From the discussion, it sounded like the spec doesn't match any existing implementation, and the resolution brings the spec closer to alignment with implementations.  We might need a bug once there's concrete spec text and updated tests here, but for now there's no concrete change to implement, I think.
