### ISSUE TITLE
[css-contain-2] filter effects and "relevant to the user"

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#945]
A resolution was made for [csswg-drafts/#7711](https://github.com/w3c/csswg-drafts/issues/7711).

**\[css\-contain\-2\] filter effects and "relevant to the user"**

* RESOLVED: Add a SHOULD requirement for considering the filter effect extent and interaction with UA margin

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7711#issuecomment-1301503000)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
Probably worth having a bug to confirm that our impl in https://bugzilla.mozilla.org/show_bug.cgi?id=1791759 lives up to this should requirement (or understand/document the limitations).

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1798813
