### ISSUE TITLE
[css-contain][css-sizing] `content-visibility: auto` kinda broken by not using last remembered size with `contain: size`

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#955]
A resolution was made for [csswg-drafts/#7807](https://github.com/w3c/csswg-drafts/issues/7807).

**\[css\-contain\]\[css\-sizing\] \`content\-visibility: auto\` kinda broken by not using last remembered size with \`contain: size\`**

* RESOLVED: Take second solution for this case. Update the last remembered size if element doesn't skip its contents.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7807#issuecomment-1317388716)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
It looks like we need to implement the resolved-on solution, so I'll add the `bug` label to get a bug to track that.

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1800955
