### ISSUE TITLE
[css2?] Define when border rounding happens, and to which properties it applies

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#956]
A resolution was made for [csswg-drafts/#5210](https://github.com/w3c/csswg-drafts/issues/5210).

**\[css2?\] Define when border rounding happens, and to which properties it applies**

* RESOLVED: Add this definition to values\-4 and evaluate new definition against existing test suite.

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5210#issuecomment-1317420946)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
No bug needed; the resolution is just speccing the existing interoperable behavior.
