### ISSUE TITLE
[css-display] Why is display listed as not animatable instead of animation type: discrete?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#966]
A resolution was made for [csswg-drafts/#6429](https://github.com/w3c/csswg-drafts/issues/6429).

**\[css\-display\] Why is display listed as not animatable instead of animation type: discrete?**

* RESOLVED: adopt this proposal, and work out the details

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6429#issuecomment-1332439874)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
duplicated by https://github.com/mozilla/wg-decisions/issues/1131
