### ISSUE TITLE
[css-contain-2] Spec is unclear about whether 0-sized boxes can be "relevant to the user" (since they have zero intersection area)

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#974]
A resolution was made for [csswg-drafts/#5641](https://github.com/w3c/csswg-drafts/issues/5641).

**\[css\-contain\-2\] Spec is unclear about whether 0\-sized boxes can be "relevant to the user" \(since they have zero intersection area\)**

* RESOLVED: Match intersection observer behavior for this definition

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5641#issuecomment-1341356265)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
I suspect we need a bug, since this impacts `content-visibility:auto` which we now have an implementation of (in https://bugzilla.mozilla.org/show_bug.cgi?id=1791759 ).

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1804507
