### ISSUE TITLE
[scroll-animations-1] Order of pause, setTimeline

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#975]
A resolution was made for [csswg-drafts/#5653](https://github.com/w3c/csswg-drafts/issues/5653).

**\[scroll\-animations\-1\] Order of pause, setTimeline**

* RESOLVED: Accept the proposal in https://github.com/w3c/csswg\-drafts/issues/5653\#issuecomment\-1271689506

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5653#issuecomment-1341781238)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
No need to update.
