### ISSUE TITLE
[scroll-animations] Should animation events fire every time active range is left / reentered?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#976]
A resolution was made for [csswg-drafts/#4324](https://github.com/w3c/csswg-drafts/issues/4324).

**\[scroll\-animations\] Should animation events fire every time active range is left / reentered?**

* RESOLVED: Animation events fire for scroll linked animations as defined by web animations spec

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4324#issuecomment-1341786309)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
Close this because we just need to align the implementation with web animation spec. (i.e. I expect we don't have to change the implementation.)
