### ISSUE TITLE
[scroll-animations-1] currentTime when scroll range is 0 (again)

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#981]
A resolution was made for [csswg-drafts/#7778](https://github.com/w3c/csswg-drafts/issues/7778).

**\[scroll\-animations\-1\] currentTime when scroll range is 0 \(again\)**

* RESOLVED: Scroll animation is inactive when denominator is 0

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7778#issuecomment-1341822948)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by BorisChiou** [comment]
reuse https://bugzilla.mozilla.org/show_bug.cgi?id=1780865
