### ISSUE TITLE
[css-display-3] text run ?

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#985]
A resolution was made for [csswg-drafts/#7768](https://github.com/w3c/csswg-drafts/issues/7768).

**\[css\-display\-3\] text run ?**

* RESOLVED: Change the term “text run” to “text sequence” in css\-display\-3

[Discussion.](https://github.com/w3c/csswg-drafts/issues/7768#issuecomment-1360013043)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by aethanyc** [comment]
The resolution is a change to the spec text.
